### ISSUE TITLE
Fix SideBySide.ConnectSync.ConnectTimeout under Travis CI

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#100]
The `SideBySide.ConnectSync.ConnectTimeout` test frequently takes longer than its allowed 3500ms, causing the build to fail. It is almost always fixed by rerunning the build on Travis CI (but external contributors can't force that).

Investigate whether this actually indicates a real problem and how to fix it.

**Comment by caleblloyd** [comment]
Synchronous connections commonly wait for a thread due to #62 when the system is under load.

Synchronous Connect still calls `ConnectAsync().GetAwaiter().GetResult()` on .NET core because there is no synchronous connect method.  A couple workarounds come to mind:

- could try upping the [MinThreads in project.json](https://github.com/bgrainger/MySqlConnector/blob/master/tests/SideBySide.New/project.json#L37)
- could increase the timeout, since this is a known issue

**Comment by caleblloyd** [comment]
Haven't seen this in a while, going to close.  If we hit again, let's up MinThreads above to 16 and see if that fixes.
