### ISSUE TITLE
Have enough connection but still getting Host 'x.x.x.x' blocked because of many connection errors; unblock with 'mysqladmin flush-hosts'

### ISSUE THREAD

**Issue by KamranShahid** [mysql-net/MySqlConnector#1021]
I am using .net core 3.1 with mysql connector 8.0.21.
In mysql i have max_connection around 3000 and max_user_connection as 0 (unlimited)

In my connection pools setting in various application my total connection reserved are around 2800.
Still sometime i am getting this above error occasionally.
Any idea what could be the problem

**Comment by bgrainger** [comment]
Cross-posted to https://stackoverflow.com/questions/68836869/have-enough-connection-but-still-getting-host-x-x-x-x-blocked-because-of-many

"mysql connector 8.0.21" is the MySql.Data NuGet package; this repo is for [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/).

You can post bug reports for that package to bugs.mysql.com.

**Comment by bgrainger** [comment]
You could try replacing MySql.Data with MySqlConnector to see if that resolves your issue, though.

**Comment by KamranShahid** [comment]
Problem is i am having an year old production system on which rolling out the update in multiple components is not easy. purpose of posting here the issue also to investigate that is there any such problem faced by other's as well

**Comment by KamranShahid** [comment]
I am able to solve problem by identifying the reason was some monitoring tool (nagios) sending telnet request which eventually blocking the host as it is not authenticating the requests
