### ISSUE TITLE
GetSchema.Rows return all tables from a connection while should return only for the specified database

### ISSUE THREAD

**Issue by RODevVro** [mysql-net/MySqlConnector#1023]
Hi,

I use the connector to connect to a MariaDB database latest version. In this connection, there are several databases:
![image](https://user-images.githubusercontent.com/88318487/130074989-70ac28d3-2fdb-418c-a00e-a56b53d4a7bb.png)

I want to retrieve the list of tables in the "nation" database without the rest (system table, demo).

```
var conn = new MySqlConnection("server=YOURSERVER;user=YOURUSERID,Database=nation;password=YOURPASSWORD")
var schema = connexion.GetSchema("Tables");
var tables = schema.Rows.cast... //schema.Rows -> 100+ elements
```

Why in "schema.Rows" I have a list of all the tables in all the databases? Why don't I have only the list of the "nation" tables passed in parameter of the connectionString ?

Is this the right way to do it?

**Comment by bgrainger** [comment]
This is by design. The schema is for the server, not any particular database.

To retrieve more limited information, you would pass [schema restrictions] to the `GetSchema` method. This is not yet implemented: https://github.com/mysql-net/MySqlConnector/issues/374

For now, you can filter the results by `TABLE_SCHEMA` to limit just to the database you're interested in.
