### ISSUE TITLE
Support `UseAffectedRows` option

### ISSUE THREAD

**Issue by Nick-Lucas** [mysql-net/MySqlConnector#104]
Entity Framework throws `DbUpdateConcurrencyException` whenever an Update is run which 'affects' 0 rows.

Currently [Pomelo implements this library](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) for EntityFramework and selects ROW_COUNT() after updates to find out if a row was impacted, which returns the number of changed rows by default.

When passing a row to Update where no values have actually changed (possible when working RESTfully) , this will return 0 as MySql will automatically not change any data. This throws the exception and causes batch updates to roll back. 

Allowing the `UseAffectedRows` option on connection strings will open up user configuration, to return the number of rows which WOULD be affected if the Update changed data, instead of the number which were actually updated.

Currently setting this option in the connection string throws `NotSupportedException: UseAffectedRows=False is not supported`

**Comment by caleblloyd** [comment]
I wonder why the EF change tracker is submitting a row for update that hasn't changed.

Could you open a corresponding issue in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql and include a model / controller in which you can get the change tracker to submit a row that hasn't actually changed?

**Comment by caleblloyd** [comment]
Regardless of the EF version, this should be implemented.  If `UseAffectedRows=true`, the [FoundRows](https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/Serialization/ProtocolCapabilities.cs#L16) flag should be set in the [HandshakeResponse41Packet](https://github.com/mysql-net/MySqlConnector/blob/8477ec6da030162cf4e894d0b1c9ae72aceb9c4e/src/MySqlConnector/Serialization/HandshakeResponse41Packet.cs)

**Comment by caleblloyd** [comment]
Ok good to hear EF change tracking isn't broken. We will implement UseAffectedRows. The second comment is just details on how to implement it.

**Comment by bgrainger** [comment]
Some more background from the [documentation for `ROW_COUNT`](http://dev.mysql.com/doc/refman/5.7/en/information-functions.html#function_row-count):

> ROW_COUNT() returns a value as follows:
> 
> DML statements other than SELECT: The number of affected rows.
> 
> For `UPDATE` statements, the affected-rows value by default is the number of rows actually changed. If you specify the `CLIENT_FOUND_ROWS` flag to `mysql_real_connect()` when connecting to mysqld, the affected-rows value is the number of rows “found”; that is, matched by the `WHERE` clause.

Thus, implementing `UseAffectedRows=false` will also change the value returned by `ROW_COUNT()` (as well as the return value of `ExecuteNonQuery`).

**Comment by bgrainger** [comment]
When this is implemented, the default value (in this library) should be changed back to `false` to match `MySql.Data`; changing the behaviour of `ROW_COUNT()` is too big a breaking change for users migrating to this library.

**Comment by caleblloyd** [comment]
I've got the PR ready, but would like to discuss the default value first.

[Connector-j](https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-configuration-properties.html) sets `UseAffectedRows=false`.  Their documentation explicitly states that `UseAffectedRows=true` is not JDBC-compliant

It looks like [MySql.Data](https://dev.mysql.com/doc/connector-net/en/connector-net-connection-options.html) hard coded `UseAffectedRows=false` until Connector/Net version 5.2.6, and their decision to keep the default as false was to maintain BC.

MySqlWorkbench, based off [Connector/C++](https://github.com/mysql/mysql-connector-cpp/blob/4ac7bbc847187fa957b30c1808c5b87023bb6feb/driver/mysql_connection.cpp#L185) does not set the `Found Rows` flag by default.  PHP's PDO also does not set the `Found Rows` flag by default either.  They are both running with the equivalent default of `UseAffectedRows=true`

I'm going to guess that most other languages also do not set the `Found Rows` flag by default.  It looks like Java does to be JDBC compliant, and C# does because they did at first and are maintaining BC.

Our [Connection Options](https://mysql-net.github.io/MySqlConnector/connection-options/) page says that for "Other Options", we set them to "sensible defaults and typically do not need to be tweaked".  I think that if we follow this, we should default it to `UseAffectedRows=true`, since this seems to be the overwhelming behavior of MySql connectors in general.

If we take this approach, we should create another page in the docs that is a tutorial "Migrating from Oracle's Connector-Net", describe where we differ, and provide connection string options needed to stay fully BC.

**Comment by Nick-Lucas** [comment]
> I think that if we follow this, we should default it to UseAffectedRows=true, since this seems to be the overwhelming behavior of MySql connectors in general.

Just a couple of notes to expand on this:

* Entity Framework Core will throw `DbConcurrencyException` if it gets back 0 when it expects a row to be updated. 
* Since this exception exists and is checked for, it would seem more Entity Framework compliant to set `UseAffectedRows=false` by default
* I have noticed that the NpgSql (postgres) Provider also uses the equivalent of `UseAffectedRows=true` as the error does not throw in the scenario which led to raising this Issue, so there is precedent to go either way with regard to EFCore

**Comment by bgrainger** [comment]
I'm OK with `UseAffectedRows=true`. (After all, I picked it as the current default to align with the ADO.NET documentation: "For UPDATE, INSERT, and DELETE statements, the return value is the number of rows affected by the command.")

Since we do pick different defaults to MySql.Data (e.g., `ConnectionReset=true`, which I don't want to change), creating documentation on known issues for migrating is a good way to address both these (potentially) breaking changes for users changing libraries.

**Comment by caleblloyd** [comment]
Another argument in favor of `UseAffectedRows=true` by default is that the [DbCommand.ExecuteNonQuery](https://docs.microsoft.com/en-us/dotnet/core/api/system.data.common.dbcommand#System_Data_Common_DbCommand_ExecuteNonQuery) function states that it returns:

> Int32 The number of rows affected.

**Comment by bgrainger** [comment]
> Entity Framework Core will throw DbConcurrencyException if it gets back 0 when it expects a row to be updated.

I still don't understand this use case fully, nor the full code path that triggers it. (I'm not very familiar with EF or Pomelo.) @Nick-Lucas do you have a code sample that reproduces it so I can learn more?

**Comment by Nick-Lucas** [comment]
@bgrainger I don't have useful code sample for debugging right now, but have been planning to put one together as I ran into more serious issues which led to moving onto Postgres. I will be happy to put together a use case if it's helpful to you.

The basic story right now, is Entity Framework checks the number of rows matched/affected (depending on the provider setup) and throws if it gets back 0. This is to protect data and allow for application recovery when the model in memory falls out of sync with the model on the database. An example of this is if another application has modified that table row since it was loaded - hence DbConcurrencyException

**Comment by caleblloyd** [comment]
@Nick-Lucas I'd be happy to work through bug reports with you on EF.  I work on the [Pomelo.EntityFrameworkCore.MySql](https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql) project also, please open bugs there if you can!  We really appreciate bug reports as we're trying to harden the Pomelo library for it's 1.0.1 release, which switches the ADO.NET connector to this library.

If you include the Controller/Model that is creating problems for you, I can add them as test cases to make sure everything is working properly.

**Comment by bgrainger** [comment]
> If we take this approach, we should create another page in the docs that is a tutorial "Migrating from Oracle's Connector-Net", describe where we differ, and provide connection string options needed to stay fully BC.

Opened #114.

**Comment by Nick-Lucas** [comment]
Sure @caleblloyd I'll try and get a barebones reproduction together tonight.

**Comment by caleblloyd** [comment]
Published in [MySqlConnector 0.5](https://www.nuget.org/packages/MySqlConnector/)

EF published in [Pomelo.EntityFrameworkCore.MySql 1.0.1-prerelease-10019](https://www.myget.org/Package/Details/pomelo?packageType=nuget&packageId=Pomelo.EntityFrameworkCore.MySql)
