### ISSUE TITLE
Connection disposal does not end open transaction

### ISSUE THREAD

**Issue by Timovzl** [mysql-net/MySqlConnector#1150]
**Software versions**
MySqlConnector version: 2.1.8
Server type: Local MySQL 8 docker container ("mysql:latest"), but also RDS MySQL 8
.NET version: .NET 6

**Describe the bug**
I ran into a situation where an ongoing database transaction was not terminated (i.e. rolled back) when the `DbConnection` object was disposed. Is this by design?

The problem is that such a transaction may still be holding locks. Until the connection happens to get reused, those locks are held.

In my specific scenario, I had a manual query like this:

```sql
BEGIN;

SELECT
#snip
FOR UPDATE;
```

Since the `DbConnection` is the object wrapped in a `using` or `await using` statement, that is the thing we can trust to get cleaned up. Needing a try/catch or try/finally block with a manual `ROLLBACK` would be quite... ugly.

**Expected behavior**
I was caught off guard by the bug caused by the current behavior (if I've deduced it correctly). I would expect that closing a `DbConnection` object at least terminates any ongoing database transaction. I understand that this can be achieved via `DeferConnectionReset=False`, but that seems like overkill.

Could the current behavior be improved on without sacrificing too much performance? Alternatively, do you have any suggestions that I can use in my own code, cleaner than adding a catch or finally clause to terminate the transaction? Ideally, I'd like to prevent myself and other developers from running into the problem in the future.

**Comment by bgrainger** [comment]
The standard way to handle this in ADO.NET would be:

```csharp
using var connection = new MySqlConnection("...");
await connection.OpenAsync();

// some code ...

using (var transaction = await connection.BeginTransactionAsync())
{

    await connection.CommitAsync();
} // transaction will be rolled back here if an exception is thrown

// other code ...
```

Currently, `MySqlConnection` has no way to know that `BEGIN [TRANSACTION];` was called, so `Dispose` doesn't issue an explicit `ROLLBACK;`. Consequently, if you're manually issuing transactions, you will also have to manually issue `ROLLBACK`s. But I would recommend using the `MySqlTransaction` class instead if possible.

Since closing a connection simply returns it to the pool, the transaction will remain open. I assume that resetting the connection will roll back the transaction, but I've never actually tried that. However, that won't happen until the connection is retrieved from the pool: https://github.com/mysql-net/MySqlConnector/issues/178.

**Comment by Timovzl** [comment]
Thanks @bgrainger. I was afraid that might be the case. It makes sense. It was one trap I did not anticipate, though!

I have added a try/finally with a `ROLLBACK` for now, and will aim to stick to ADO.NET-initiated transactions in the future.

> I assume that resetting the connection will roll back the transaction, but I've never actually tried that.

That is my assumption as well, although I haven't specifically tested this behavior.
