### ISSUE TITLE
Retrieval of last inserted Id returns zero

### ISSUE THREAD

**Issue by ummerland** [mysql-net/MySqlConnector#1230]
Hi Community

We are working with MySqlConnector as a drop in replacement for MySql.Data in combination with Dapper (Contrib) in .NET6, MySqlConnector (NuGet) 2.1.13 and MariaDB 10.7.
The `InsertAsync` Method should return the inserted Id for non-list objects according to its summary and [code](https://github.com/DapperLib/Dapper.Contrib/blob/cf24f6bdc577b1e071c3764ddfb2cf3382531405/src/Dapper.Contrib/SqlMapperExtensions.cs#L377). **However, it always returns 0.**
In Dapper this is accomplished by calling `SELECT LAST_INSERT_ID() id` after a successful `INSERT`. This can also be seen in the `queries.log` on the server:

```
10 Query	SET NAMES utf8mb4
10 Query	INSERT INTO ....
10 Query	SET NAMES utf8mb4
10 Query	SELECT LAST_INSERT_ID() id
```
It runs a `SET NAMES utf8mb4` before almost every call. This may have been decided in #626.

With MySql.Data this functionality works as expected. It does instead call a `InitDB` on a database called _testdatabase_:

```
12 Init DB	testdatabase
12 Query	INSERT INTO ...
12 Init DB	testdatabase
12 Query	SELECT LAST_INSERT_ID() id
```

**Assumption:**
It seems that `SET NAMES utf8mb4` clears the `LAST_INSERT_ID` field on the database instance somehow. I cannot find a definitive statement on this however.

**Expected behavior:**
Querying `LAST_INSERT_ID()` returns the actual last inserted Id.
Maybe the `SET NAMES utf8mb4` can be elliminated in favour of a `Init DB` call?

**Comment by bgrainger** [comment]
`SET NAMES utf8mb4` is executed when a connection is reset, which occurs when it's inserted back into and retrieved from the pool.

Your log implies the following sequence of events:

```csharp
using (var connection = new MySqlConnection(...))
{
    connection.Open();
    connection.Execute("INSERT INTO ...");
}
using (var connection = new MySqlConnection(...))
{
    connection.Open();
    connection.Execute("SELECT LAST_INSERT_ID()");
}
```

If that's what's happening, your code is invalid, and _cannot_ be relied on to give the right answer. There's no guarantee that the second command will run on the same connection as the first command, so it may return a completely incorrect ID value.

This is actually a bug in MySql.Data (returning stale data from a previous connection) that MySqlConnector fixes.

The fix is to restructure your code to something like the following:

```csharp
using (var connection = new MySqlConnection(...))
{
    connection.Open();
    connection.Execute("INSERT INTO ...");
    connection.Execute("SELECT LAST_INSERT_ID()");
}
```

Depending on how you're using Dapper, this _may_ be as simple as calling `connection.Open()` before you execute the first Dapper operation. Dapper transparently opens and closes connections, which could cause this problem.

If you can still reproduce the bug even once you're using proper connection management, please reopen this issue.

**Comment by xywf221** [comment]
I recently encountered the same issue. When using MySql.Data, SELECT LAST_INSERT_ID() would return the expected value. However, after switching to MySqlConnector, the return value would be 0. While debugging Dapper, I found that if the connection was initially closed, Dapper would first open it and finally close the connection. After extensive troubleshooting, I discovered that when using MySql.Data, there was no manual Open Connection code, but the connection state was Open. MySqlConnector does not behave this way; it requires us to open the connection before executing the insert SQL.

good code
``` c#
var connection = dataSource.CreateConnection();
// open!!!
connection.Open();
connection.Execute(
    "insert into postal (letter_id,recipient_id,sender_name,unlimit,money, item) values (@letterId, @recipientId, @senderName, @unlimit, @money, @item);",
    postals);
var b = connection.ExecuteScalar<int>("select last_insert_id();");
```
