### ISSUE TITLE
Opening a connection on mariadb 10.10.2 fails due to collations with null charsets

### ISSUE THREAD

**Issue by StefanBilliet** [mysql-net/MySqlConnector#1244]
**Software versions**
MySqlConnector version: 2.2.1
Server type (MySQL, MariaDB, Aurora, etc.) and version: mariadb 10.10.2 (currently mariadb:latest on docker hub)
.NET version: dotnet 7
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Opening a connection using MysqlConnector fails. When stepping through the decompiled code, I see that the exception occurs in `LoadCharacterSets`. The db in question is freshly created and empty. When executing `SHOW COLLATION`, I noticed there are a bunch of records with a null charset and null id:
<img width="965" alt="image" src="https://user-images.githubusercontent.com/2368922/203574671-274b62a6-41df-438a-a383-71653087b110.png">

**Exception**
System.InvalidCastException
Object cannot be cast from DBNull to other types.

**Comment by bgrainger** [comment]
> I see that the exception occurs in `LoadCharacterSets`

There's no such function in MySqlConnector. Did you mean to report this bug for MySql.Data? https://github.com/mysql/mysql-connector-net/blob/3ebd5c49432a7bcff96438a7f9b193576acda30a/MySQL.Data/src/Driver.cs#L327. You can do so at bugs.mysql.com.

Of course, I would strongly recommend switching to MySqlConnector, since it has fixed a lot of bugs that are present in MySql.Data. https://mysqlconnector.net/tutorials/migrating-from-connector-net/

**Comment by StefanBilliet** [comment]
I'm terrible sorry, my mistake.
