### ISSUE TITLE
Mysql data.dll

### ISSUE THREAD

**Issue by IsmaelMagdy** [mysql-net/MySqlConnector#1297]
Mysql data.dll not appear when i add a refrance (framework or extenion)

**Comment by bgrainger** [comment]
MySql.Data.dll is not associated with this project (MySqlConnector). Running `dotnet add package MySqlConnector` will add MySqlConnector.dll to your project. Reasons for using MySqlConnector instead of MySql.Data are given here: https://mysqlconnector.net/tutorials/migrating-from-connector-net/.

For problems with MySql.Data.dll you can report bugs at https://bugs.mysql.com/ or https://forums.mysql.com/.
