### ISSUE TITLE
Min/MaximumPoolsize

### ISSUE THREAD

**Issue by kwaazaar** [mysql-net/MySqlConnector#133]
Hi,

I see different behaviour between MySql.Data and MySqlConnector regarding connectionpooling. If I use MySql.Data with a MaximumPoolsize set to 10 in the connectionstring, it opens approx. 5 connections to do all its work. When I use MySqlConnector, it seems to open 8 connections to do the same work in the same amount of time.

Does MySqlConnector perhaps use a MinimumPoolSize of 8 or use a different algorithm to decide if it needs to wait for an existing pooled connection of if to create a new one?

NB: This is not a serious problem, it's just an observation. As far as I can see, MySqlConnector still respects the configured MaximumPoolsize.

Regards,
Robert

**Comment by caleblloyd** [comment]
Right now MySqlConnector does not do anything if Minimum Pool Size is set, until https://github.com/mysql-net/MySqlConnector/issues/85 is implemented.

MySql.Data and MySqlConnector have generally the same pooling algorithm:

`connection.Open()` or `await conection.OpenAsync()`
- try to retrieve an open connection from the pool
- if there are no open connections, and `poolSize < MaximumPoolsize`, open a new connection
- if `poolSize == MaximumPoolsize`, wait for a connection to finish

`connection.Close()`
- return the connection to the pool

You may run your app over and over and see different results for how many connections actually get opened.  This is because different things can happen between `Connection.Open()` and `Connection.Close()` that can affect timing.
- Database can take different amounts of time to service the same query, depending on how busy it is
- Variable latency between App Server and Database Server
- Operating System can service other processes
- .NET can run garbage collection

Generally, if you implement all of your ADO.NET calls as async you will get very good performance with MySqlConnector.  Check out our [Best Practices](https://mysql-net.github.io/MySqlConnector/tutorials/best-practices/) documentation
