### ISSUE TITLE
An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by dvthang90** [mysql-net/MySqlConnector#1358]
**Software versions**
MySqlConnector version: 2.2.7
Server type (MySQL, MariaDB, Aurora, etc.) and version:  MYSQL 8.0.31
.NET version:  NET FRAMEWORK 4.7.2
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Sometimes get error "An existing connection was forcibly closed by the remote host"
**Exception**
![image](https://github.com/mysql-net/MySqlConnector/assets/27855952/e87e816c-a485-4e17-8df0-f5c4ae5dfc1c)

**Code sample**
ConnectionString:
![image](https://github.com/mysql-net/MySqlConnector/assets/27855952/2ce5df30-80a6-4f53-831e-f08365812caf)
Code GetData:
![image](https://github.com/mysql-net/MySqlConnector/assets/27855952/0286c138-963d-410a-9dee-0f570788577c)

**Expected behavior**
The cause of the above error and how to thoroughly handle it

**Comment by bgrainger** [comment]
The problem is exactly what the message says: the remote MySQL Server closed the connection. MySqlConnector can't send data on a closed connection.

It looks like you're using Polly, which is what I'd recommend for retries here. How many times did the application retry before it failed?

Please don't post images. https://idownvotedbecau.se/imageofanexception/ https://idownvotedbecau.se/imageofcode

**Comment by dvthang90** [comment]
Hi @bgrainger . I want to know why it gives the error "the remote MySQL Server closed the connection" because before I used mysql.data 8.0.31 I didn't get the above error.

**Comment by bgrainger** [comment]
Duplicate of #1359
