### ISSUE TITLE
Build: Update to .NET Core Tools MSBuild

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#138]
See announcement here: https://blogs.msdn.microsoft.com/dotnet/2016/11/16/announcing-net-core-tools-msbuild-alpha/

Migrate the projects away from `project.json` back to csproj.

**Comment by caleblloyd** [comment]
I just did this for a work project and it's no easy feat.

Visual Studio 2015 didn't support the migrated `.csproj` files out of the box, and even after fixing some issues it still didn't display correctly.  The only way I could get them to load on Windows was using VS 2017 RC.

Also, when I ran `dotnet migrate` with [cli version 1.0.0-preview3-004056](https://github.com/dotnet/core/blob/master/release-notes/preview3-download.md), I couldn't get `dontet restore` to work afterwards.  I had to upgrade the CLI to `1.0.0-preview4-004233`

I'm still working through issues, the ecosystem needs more time to mature.

**Comment by bgrainger** [comment]
I wasn't even going to start work on this until VS 2017 RTM was shipping.

**Comment by bgrainger** [comment]
.NET Core Tools 1.0 is released (with VS2017): https://blogs.msdn.microsoft.com/dotnet/2017/03/07/announcing-net-core-tools-1-0/

**Comment by caleblloyd** [comment]
I can do this tonight, I just went through it with `Pomelo.EntityFramework`

Since not all IDEs support `msbuild` yet, I recommend that we branch off current master to a `project_json` branch.  We can cherry-pick everything except for the `msbuild` changes into that branch so that developers on different IDEs can still contribute.

Project Rider is one notable example that does not support `msbuild` fully yet.  I suspect that the ecosystem will catch up over the next couple months, in which case we can remove the `project_json` branch

**Comment by caleblloyd** [comment]
I've also got a CI improvement planned where we can use the [microsoft/dotnet](https://hub.docker.com/r/microsoft/dotnet/) docker image.  This should speed up Travis by a minute or so.  I'll roll it into this changeset since CI will need the new `dotnet` version anyways

**Comment by caleblloyd** [comment]
> I've also got a CI improvement planned where we can use the microsoft/dotnet docker image

Going to hold off on this for now, I'm having trouble getting it working in travis.  Will revisit later.
