### ISSUE TITLE
Performance degradation when create a connection per each small request

### ISSUE THREAD

**Issue by stretyak** [mysql-net/MySqlConnector#1523]
**Software versions**
MySqlConnector version: 2.3.7
Server type (MySQL, MariaDB, Aurora, etc.) and version:  MySQL 5.6.43-log
.NET version: netcoreapp3.1
(Optional) ORM NuGet packages and versions: 

**Describe the bug**
Open a MySqlConnection connection, create a command, excecute a reader
repeate the same step 10000 times
see how slow it is.

at the same time if you open a connection once and then create 10000 commands using the same connection the job is done dramatically faster.

The connection string is simple. Polling is activated. the test is a simple one thread test.

At my laptop the difference between 2 below sample is a minute
the slow sample takes 1 minute
the fast sample takes 2 seconds.

What am I doing wrong?

**Code sample**

```
the below is very **fast**:
		using (var connection = new MySqlConnection(connStr))
		{
			connection.Open();

			for (int i = 0; i < 10000; i++)
			{
				var cmd = new MySqlCommand("a_proc_that_returns_no_rows", connection)
				{
					CommandType = System.Data.CommandType.StoredProcedure,
				};

				using (var r = cmd.ExecuteReader())
				{
				}
			}
		
but the below one is much **slower**

		for (int i = 0; i < 10000; i++)
		{
			using (var connection = new MySqlConnection(connStr))
			{
				connection.Open();
				var cmd = new MySqlCommand("a_proc_that_returns_no_rows", connection)
				{
					CommandType = System.Data.CommandType.StoredProcedure,
				};

				using (var r = cmd.ExecuteReader())
				{
				}
			}
		}


```

**Expected behavior**
The results should be almost the same because the polling is activated and it is advised to create a connection each time and not to keep it opened and to reuse.

**Comment by bgrainger** [comment]
Retrieving a connection from the pool is cheaper than opening a new connection, but it's not zero cost; this is by design.

Because server sessions are shared between different `MySqlConnection` objects, the default setting for MySqlConnector is to issue a `COM_RESET_CONNECTION` command on the session before returning as a new `MySqlConnection`. This clears any temporary tables or user-defined variables and prepares the session for reuse. There will be a small amount of latency incurred for doing this.

You can disable this by specifying `Connection Reset=false` in your connection string: https://mysqlconnector.net/connection-options/#ConnectionReset. This may be appropriate if you want higher performance and shared session state won't impact your application.

**Comment by stretyak** [comment]
Yes, you are right. I have set the "Connection Reset" to be false and now the same test with 10000 requests takes 2 seconds instead of 1 minute. But it is not a "small amount of latency" - the difference 60 seconds and 2 seconds.
can it be such a lot because my sql server is 5.6 version and COM_RESET_CONNECTION was intoduced in 5.7 it seems.
Means :
if "Connection Reset" = true and mysql version is 5.6 - then the reset happens with full-reauthntication which is expensive.
if "Connection Reset" = true and mysql version is 5.7 - then the reset happens with COM_RESET_CONNECTION command which is cheap.
is it correct?

**Comment by bgrainger** [comment]
> if "Connection Reset" = true and mysql version is 5.6 - then the reset happens with full-reauthntication which is expensive.
> if "Connection Reset" = true and mysql version is 5.7 - then the reset happens with COM_RESET_CONNECTION command which is cheap.

Thanks for pointing that out. Yes, due to lack of support in MySQL 5.6, MySqlConnector will simulate connection reset with a full reauthentication, which is slower. I don't have a benchmark to know how much slower, but `COM_RESET_CONNECTION` was introduced for the purpose of speeding this up.

(MySQL 5.6 has been end-of-life for so long that I forgot about that. I would also recommend updating to 8.0 or 8.4; even 5.7 is now unsupported.)
