### ISSUE TITLE
Libuv Network Pipeline Performance

### ISSUE THREAD

**Issue by caleblloyd** [mysql-net/MySqlConnector#163]
I implemented the experimental [System.IO.Pipelines.Networking.Libuv](https://dotnet.myget.org/feed/dotnet-corefxlab/package/nuget/System.IO.Pipelines.Networking.Libuv) package as a drop-in replacement for TcpClient in https://github.com/caleblloyd/MySqlConnector/commit/9907f999493127224bc3bf9fc7c2023b49df01f1

Here's some quick performance results.  These are on a 4-Core i6600-K Desktop (not the same machine as in https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/126, don't compare times)

|Test | MySqlConnector 0.11.2 | LibUV Network Pipeline | % Difference |
|---|---|---|---|
|10,000 Async Inserts in loop |  1.63s Average | 0.87s Average | +86.7% |
|Max Sustained Async RPS with response time <1s | 1800 RPS | 2800 RPS | +55.5% |

`System.IO.Pipelines.Networking.Libuv` is fairly new and still very much experimental, so it won't make it into MySqlConnector anytime soon.

LibUV may present a nice way for us to develop performance enhancements, however.  The UV thread takes care of all of the networking on it's own thread using non-blocking I/O, is highly performant, and should use little CPU.  This leaves the .NET threads open to execute all of the code in our library since they won't be doing networking tasks.

**Comment by Kagamine** [comment]
When we will use libuv instead of tcpClient?

**Comment by bgrainger** [comment]
Note that 0.11.3 significantly improved async performance (see #164), which was after these benchmarks were taken. #245 also made some significant improvements. So the original benchmark in this issue is out-of-date and the difference between TcpClient and libuv may be much less; we would need to test again.

Note however in the latest benchmarks for #245, `ExecuteScalarNewAsync` is still 50% slower than `ExecuteScalarNewSync`; my investigation into that seems to point to extra overhead in the async `Socket` methods. If that overhead is unavoidable, then libuv may still be a significant improvement.

**Comment by bgrainger** [comment]
Any future work in this area will use the official [System.IO.Pipelines](https://www.nuget.org/packages/System.IO.Pipelines/) package, possibly using the [Pipelines.Sockets.Unofficial](https://blog.marcgravell.com/2018/07/pipe-dreams-part-2.html) library (from NuGet or from source).
