### ISSUE TITLE
CHARSET latin1 to UTF8 issues

### ISSUE THREAD

**Issue by xyting** [mysql-net/MySqlConnector#233]
I have a table in database with CHARSET=latin1;
```sql
DROP TABLE IF EXISTS `currency_info`;
CREATE TABLE `currency_info` (
  `alphabetic_code` varchar(18) NOT NULL COMMENT '字母代码',
  `numeric_code` varchar(18) NOT NULL COMMENT '数字代码',
  `minor_unit` smallint(2) NOT NULL COMMENT '辅助单位',
  `currency_name` varchar(127) NOT NULL COMMENT '货币名称',
  `modify_time` datetime NOT NULL COMMENT '更新时间',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`alphabetic_code`),
  KEY `idx_modify_time` (`modify_time`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
```
and then I use follow SQL to get table structure
```sql
SELECT COLUMN_NAME, DATA_TYPE, IS_NULLABLE, COLUMN_KEY, COLUMN_DEFAULT, COLUMN_COMMENT FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA='databaseName' AND TABLE_NAME='currency_info'
```

I want to get the COMMENT, 
```csharp
using (var command = new MySqlCommand(sql, _connection))
                using (var reader = command.ExecuteReader())
                    while (reader.Read())
                    {
                        var column = new  {
                             Comment = reader[5].ToString(),
                        };
                    }
```

The Comment is Garbled (e.g.  reader[5].ToString() return 3Î»×ÖÄ¸´úÂë)

The connection string like this
`var connectionString = "Server=127.0.0.1;database=databaseName;uid=root;pwd=123456;";`

**Comment by bgrainger** [comment]
Thanks for the detailed code sample. I'm not able to reproduce this problem with MySqlConnector or with Oracle's Connector/NET.

How are you viewing the contents of `reader[5].ToString()`? Are you printing it to the console (`Console.WriteLine`), examining it in the Visual Studio debugger, or something else? Do you get the same behavior if you switch to Connector/NET, or is it only an issue with MySqlConnector?

**Comment by xyting** [comment]
Examining it in the Visual Studio debugger and print it to the console. Tomorrow,  I'll switch to Connector/NET to test the behavior.

Thanks.

**Comment by bgrainger** [comment]
Could you paste a screenshot from MySQL Workbench (or some other tool) that demonstrates that the comments are correct in the MySQL database itself?

As you can see in this screenshot, I have the values from your snippet above in the DB and can retrieve them correctly in C#:

![image](https://cloud.githubusercontent.com/assets/188129/24870260/965920b0-1dca-11e7-8a57-e10c01ab9f71.png)

**Comment by xyting** [comment]
Thanks, I use Navicat

![bug](https://cloud.githubusercontent.com/assets/14950276/24891866/2b3ff042-1eab-11e7-8efd-ff4d174ee5fe.png)

**Comment by xyting** [comment]
OK, I see the HEX value,
COLUMN_COMMENT | HEX(COLUMN_COMMENT)
------------------------|-------------------------------
字母代码	C397C396C384C2B8C2B4C3BAC382C3AB
------------------------|-------------------------------
数字代码	C38AC3BDC397C396C2B4C3BAC382C3AB
------------------------|-------------------------------
辅助单位	C2B8C2A8C396C3BAC2B5C2A5C38EC2BB
------------------------|-------------------------------
货币名称	C2BBC3B5C2B1C392C383C3BBC2B3C386
------------------------|-------------------------------
更新时间	C2B8C3BCC390C382C38AC2B1C2BCC3A4
------------------------|-------------------------------
创建时间	C2B4C2B4C2BDC2A8C38AC2B1C2BCC3A4
------------------------|-------------------------------

**Comment by bgrainger** [comment]
Interestingly, I get different values:

COLUMN_COMMENT | HEX(COLUMN_COMMENT)
--- | ---
字母代码 | E5AD97E6AF8DE4BBA3E7A081
数字代码 | E695B0E5AD97E4BBA3E7A081
辅助单位 | E8BE85E58AA9E58D95E4BD8D
货币名称 | E8B4A7E5B881E5908DE7A7B0
更新时间 | E69BB4E696B0E697B6E997B4
创建时间 | E5889BE5BBBAE697B6E997B4

My `HEX(COLUMN_COMMENT)` values are UTF-8.

I initially wasn't sure what to make of your hex values, because they appear to use four bytes per character, and I'm not aware of any Chinese encoding that long. However, if we decode that byte string as UTF-8, we get `C397` -> U+00D7, `C396` -> U+00D6, etc. This produces the string you're seeing: `×ÖÄ¸´úÂë`. If we take just the low byte of each char, we get `D7D6C4B8B4FAC2EB`. This decodes as GBK to the original string, 字母代码.

Thus, it appears that double-encoding is going on *somewhere*, but I don't know where. MySQL Server is sending us valid UTF-8 (as requested by MySqlConnector) but it decodes into something that has to be decoded a second time (with GBK) and the client has no way of knowing that (AFAIK).

I'm running MySQL Server 5.7.15 on Windows 10. From your screenshot, it looks like you might be running 5.5.45? Is it MySQL Server Community Edition, or some other service? Which version? Which host OS?

**Comment by xyting** [comment]
Oh, I known, My Navicat client connection using GBK as default code page, so I use this connection to CREATE table so that the COMMENT is encoding with GBK.

**Comment by bgrainger** [comment]
Does it work if you create the table using Oracle's [MySQL Workbench](https://www.mysql.com/products/workbench/)? (Or write a small C# program to create the table using this library?) This is sounding like a bug in the Navicat client, that might need to be filed with them.
