### ISSUE TITLE
cancellationToken cannot handle cancel event

### ISSUE THREAD

**Issue by Kagamine** [mysql-net/MySqlConnector#285]
https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlConnection.cs#L301

This cancellation token has not been used in session. So we cannot cancel the task when connecting failed.

We hope the client is able to handle the cancel signal in each async scene.

**Comment by bgrainger** [comment]
I don't think I fully understand the problem you're describing. Is it that `OpenAsync` is taking a long time, but can't be cancelled by the `CancellationToken`? Also, I would expect an exception to be thrown "when connecting failed"; the cancellation token shouldn't be necessary.

**Comment by Kagamine** [comment]
We want to cancel the task by cancellation token in our code. But in mysqlconnector there was no logic to cancel the task.

**Comment by bgrainger** [comment]
> We want to cancel the task by cancellation token in our code.

Do you have sample code of the task that can't be cancelled? (I'm just not understanding the scenario that doesn't work.)

**Comment by Kagamine** [comment]
anyway, our goal is ensure we can cancel a task immediately, not wait an IO finished then cancel.

**Comment by Kagamine** [comment]
https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlConnection.cs#L318

Can we make the session implements the IDispose to ensure the ReturnToPool will be called?

**Comment by bgrainger** [comment]
> https://github.com/mysql-net/MySqlConnector/blob/master/src/MySqlConnector/MySqlClient/MySqlConnection.cs#L318-L320
> 
> I want to know if the ConnectAsync throw exception, Will this session return to pool?

The code you highlighted only runs if `m_connectionSettings.Pooling == false`, so that session will never be returned to a pool.

In the other case (of creating a session associated with a pool), the session won't be returned to the pool if an exception is thrown when it's being created; it's assumed to be in a failed state.

> Can we make the session implements the IDispose to ensure the ReturnToPool will be called when disposing?

I think this would be a confusing use of `IDisposable`, because the object would still be valid and usable after being disposed (and would be disposed over and over again as it was retrieved from--and returned to--the pool). I'd rather use `try{} finally{ session.ReturnToPool(); }` but I'm not aware of any places where it would be good to introduce that.

**Comment by caleblloyd** [comment]
@Kagamine you can pass the CancellationToken to `connection.OpenAsync(cancellationToken)`

> In other words, we hope the cancel behavior can be controlled by users more exactly. When received cancel signal, do not new any objects, and dispose existed objects.

Check out the ClearPool methods to dispose existing options: https://mysql-net.github.io/MySqlConnector/api/mysql-connection/

**Comment by bgrainger** [comment]
I don't think there's any action to be taken on this case; please reopen if I'm wrong.
