### ISSUE TITLE
ConnectionReset issue

### ISSUE THREAD

**Issue by Kagamine** [mysql-net/MySqlConnector#288]
Hi @bgrainger 

We don't think our service does not support connection reset. we also have tested connection reset with libmysql which is a c++ mysql client. It worked fine. So could you please keep investigating MySqlConnector? You can also get contact with xiangyh@microsoft(Xiangyu Hu) or lilia@microsoft.com(Libin Liang), they are working on the MySQL network protocol.

**Comment by bgrainger** [comment]
Azure Database for MySQL does support connection reset. However, MySqlConnector doesn't send a `COM_RESET_CONNECTION` packet because the proxy advertises itself [as version `5.6.26.0`](https://social.msdn.microsoft.com/Forums/en-US/795cb2be-dce7-4805-b324-a67e83697580/azure-database-for-mysql-reports-incorrect-version?forum=AzureDatabaseforMySQL) and `COM_RESET_CONNECTION` is only supported by `5.7.3` (and later). (Moreover, the `5.6.26.0` proxy might be in front of an MySQL 5.6 or MySQL 5.7 server, so there's no way to know without running a `select @@version;` command.)

Because `COM_RESET_CONNECTION` isn't supported, MySqlConnector sends a `COM_CHANGE_USER` packet instead. This is immediately rejected by Azure; see [my forum post](https://social.msdn.microsoft.com/Forums/en-US/adb35274-2f20-4968-8026-49a8d7ade1f0/comchangeuser-command-not-supported). See also #169 for an earlier writeup of this problem.

I'd prefer if the server could be fixed to allow `COM_CHANGE_USER` to work. However, if that's not likely to happen soon, I suppose MySqlConnector could execute `select @@version;` to get the actual server version, and use `COM_RESET_CONNECTION` if the server is really 5.7. (However, clients would still be broken if the server is actually 5.6.)

**Comment by Kagamine** [comment]
I have forwarded the proxy version issue to the proxy owner. I think our team will fix it soon.
`COM_CHANGE_USER` is already assigned to Libin, he will make it work. Thanks for these information.

**Comment by Kagamine** [comment]
@bgrainger There is a workaround with `COM_CHANGE_USER`. Now the username of Azure database for MySql is consisted of 2 parts: servername and username, like `someuser@someserver`. When you invoke COM_CHANGE_USER could you pass the username only(without `@` and servername).

If in this way it works, please ping me.

**Comment by Kagamine** [comment]
Could you email me your telephone number and free time in UTC. Our member wants to have a call with you.

**Comment by Kagamine** [comment]
*.mysqldb.chinacloudapi.cn The username likes `someuser%someserver`
*.mysql.database.azure.com The username likes `someuser@someserver`

If the workaround works ok, could you please make the workaround when match the above dns.

**Comment by bgrainger** [comment]
@Kagamine sent

**Comment by bgrainger** [comment]
@Kagamine I can't get the suggested workaround to work. If the original User ID in the connection string was `user@database`, I changed the `COM_CHANGE_USER` payload to just send `user`, 

The server returned an error: `Access denied for user 'user'@'[IP]' (using password: NO)`

Prior to this workaround, it was returning: `Access denied for user 'user@database'@'[IP]' (using password: NO)`

**Comment by bgrainger** [comment]
I realised that my test of the workaround probably contained an error; I was still sending `mysql_native_password` as the `auth plugin name` field in [`COM_CHANGE_USER` packet](http://web.archive.org/web/20170404163330/https://dev.mysql.com/doc/internals/en/com-change-user.html).

However, even if I set that to `sha256_password`, send the password as plain text, and truncate the user ID at `@`, I still can't get it to work.

**Comment by Kagamine** [comment]
The relationship between gateway and mysqld is many to many. So when you connected to the azure db for mysql, we don't know which mysql server you want to connect and the version of the server is.

**Comment by Kagamine** [comment]
@bgrainger Need add connection attributes to tell the gateway which client you are. And could you please try again the above workaround?

**Comment by bgrainger** [comment]
> Need add client info connection attributes

Which ones need to be specified? Are there any particular values they should take? (So far, the best documentation I've found on this [is here](https://dev.mysql.com/doc/refman/5.7/en/performance-schema-connection-attribute-tables.html).)

**Comment by Kagamine** [comment]
client name & version

**Comment by bgrainger** [comment]
@Kagamine I tested the User ID workaround with a build containing the changes for #293 and it works correctly, so I will add changes to truncate the user ID for the server DNS you gave.

**Comment by Kagamine** [comment]
We will keep fixing this issue, could you provide me the workaround code?

**Comment by bgrainger** [comment]
In #294, @Kagamine wrote

> We need not do the workaround with username. I think in this week we can fix the COM_CHANGE_USER
username handling issue.

Closing this issue, since #293 should cover everything that's necessary.
