### ISSUE TITLE
Update Statements hang in a DataReader loop.

### ISSUE THREAD

**Issue by Topcoder01** [mysql-net/MySqlConnector#308]
**This was the only other issue I had converting a project over to this Connector from the 6.9.9 MySQL Connector. I was able to program around it, but the code below should work. I'm not sure why it doesn't.**

 Dim oMySqlCommand1 As New MySqlCommand
 Dim oMySqlCommand2 As New MySqlCommand

oMySqlCommand1.Connection = [New Connection Object]
oMySqlCommand2.Connection = [New Connection Object]

oMySqlCommand1 .CommandText = "select c_id from customers"

oDataReader = oMySqlCommand.ExecuteDataReader

While oDataReader.HasRows
                    oDataReader.Read()
                    oMySqlCommand2 .CommandText = "update  customers_profile set activated = 1 where c_id = " &  oDataReader("c_id")

 **'Hangs on the statement below, I have no clue why, the reader is accessing 1 table, and the second connection is updating a completely different table in the same database. Both connections are created with the same connection string.** 
              
  oMySqlCommand2..ExecuteNonQuery()

End While

oDataReader.close

**Comment by bgrainger** [comment]
I translated your VB sample into (what I think is) roughly equivalent C#, although I had to change the `ExecuteDataReader` call and open the connections. (I don't know if this is handled automatically in VB or was a typo.)

```
	var oMySqlCommand1 = new MySqlCommand();
	var oMySqlCommand2 = new MySqlCommand();

	oMySqlCommand1.Connection = new MySqlConnection(csb.ConnectionString);
	oMySqlCommand2.Connection = new MySqlConnection(csb.ConnectionString);
	
	oMySqlCommand1.Connection.Open(); // new
	oMySqlCommand2.Connection.Open(); // new
	
	oMySqlCommand1.CommandText = "select c_id from customers";

	var oDataReader = oMySqlCommand1.ExecuteReader(); // changed; was oMySqlCommand.ExecuteDataReader

	while (oDataReader.HasRows)
	{
		oDataReader.Read();
		oMySqlCommand2.CommandText = "update customers_profile set activated = 1 where c_id = " + oDataReader["c_id"];
		oMySqlCommand2.CommandText.Dump();

		oMySqlCommand2.ExecuteNonQuery();
	}
	oDataReader.Close();
```

This succeeded (no hang) and updated all the rows in the database.

(Maybe this is a very simplified example, but FWIW these kind of loops can be executed in the DB server itself (which should be much faster due to fewer client/server roundtrips); e.g., `UPDATE customers_profile SET activated = 1 WHERE c_id IN (SELECT c_id FROM customers);`.)

If you're able to post a complete (minimal) program that reproduces the hang (instead of just a snippet), I'd be happy to debug it further. (Although I'm less familiar with VB, that shouldn't be a problem if it reproduces the hang.)

**Comment by Topcoder01** [comment]
```
var oMySqlCommand= new MySqlCommand();

oMySqlCommand.Connection = new MySqlConnection(csb.ConnectionString);
oMySqlCommand.Connection.Open(); // new

oMySqlCommand.CommandText = "select c_id from customers";

var oDataReader = oMySqlCommand.ExecuteReader(); 

while (oDataReader.HasRows) //Hangs here on the second pass
{
	oDataReader.Read();
        oMySqlCommand.Connection = new MySqlConnection(csb.ConnectionString);
        oMySqlCommand.Connection.Open(); // new

	oMySqlCommand.CommandText = "update customers_profile set activated = 1 where c_id = 1"

	oMySqlCommand.ExecuteNonQuery();
}
oDataReader.Close();
```

I converted this to C#, forgive me if it's not 100% syntax correct.  This works with the 6.9.9 driver from MySQL.  If I use a different command object for the inner statement in the loop, then it works like in your example and in my original wrong example.  This was one of the conversion issues I had.

**Comment by bgrainger** [comment]
Once `CommandTimeout` was implemented, the `oDataReader.Read();` call started throwing a timeout exception (after 30s by default).

I have decided not to clone Connector/NET's behaviour here; IMHO it doesn't make much sense to share a `MySqlCommand` across multiple active connections because they are fairly cheap to create. Because this is a breaking change, I'm adding a new exception that will detect this situation immediately: 8189ac6835e8e3af1a5e1715998409b96f91decc
