### ISSUE TITLE
Facing issue regarding Replication

### ISSUE THREAD

**Issue by RBSProjects** [mysql-net/MySqlConnector#318]
Hi Guys,
Sorry for asking question in issues section because I don't know how to get the answer on github.

I just started using this connector and my question is regarding replication. We have 1 master and 3 slaves, so how we have to configure this in connection string?

So that insert / update  / delete go to Master and only select to slaves in round robin?

Thanks,
Fahad

**Comment by bgrainger** [comment]
You'd have to have two connection strings, "write" = `Server=master01;User=...` and "read" = `Server=slave01,slave02,slave03;User=...`. Depending on the operation you plan to execute, the code would need to explicitly choose the correct connection string, e.g., `using (var connection = new MySqlConnection(writeConnectionString))` or `using (var connection = new MySqlConnection(readConnectionString))`.

However, when doing this, you'd run into #226: this library currently always connects to the servers in order, and doesn't round-robin between them. I'm inclined to change the default behaviour, because I suspect that having load-balanced read slaves is more common than failover, but it would be best to keep that discussion at #226.

(Note that you can work around this limitation by using a layer 4 load balancer between MySqlConnector and your DB instances, but I'd strongly recommend against that due to serious problems it can cause if operations are cancelled.)

**Comment by RBSProjects** [comment]
Hi bgrainger,

Thanks for the prompt response. Regarding Master / Slave its clear from your above answer.

But when we set 3 slaves in read connection string then your driver will send the read queries between these slaves in round robin manner or how its working. Point is how load is distributed among all slaves?

==============================
We also used MySQL Connector in that they have server group and one is marked as master and remaining are marked as slaves and read queries are sent to slaves in round robin manner.

**Comment by bgrainger** [comment]
> Point is how load is distributed among all slaves?

Currently, all traffic will go to the first slave; it's not distributed. Please watch #226 for updates about this.
