### ISSUE TITLE
Rename NuGet package?

### ISSUE THREAD

**Issue by bgrainger** [mysql-net/MySqlConnector#347]
When searching NuGet for “mysql” (https://www.nuget.org/packages?q=mysql), MySqlConnector doesn't show up till [page 6](https://www.nuget.org/packages?page=6&q=mysql).

The fourth result (on the first page) has just 286 total downloads. Thus download count doesn't seem to influence rankings significantly. However, what does seem to be a common factor of all results on the first five pages is “MySql” as a separate token in the package ID (e.g., `MySql.Data`, `Shaolinq.MySql`, or `SapientGuardian.MySql.Data`). My guess is that punctuation-delimited “words” in package IDs are weighted very heavily in relevance rankings.

“Rebranding” with a different package ID could potentially dramatically improve NuGet rankings, at the cost of breaking updates for existing users. (Thus, this should definitely be changed before 1.0.) Some migration strategies are discussed at aspnet/Home#1222, e.g., publishing one final version of `MySqlConnector` that throws exceptions telling clients to switch to the new package.

This still leaves open the question of what the new package ID should be. I'm opening this issue for suggestions and discussion.

**Comment by ejball** [comment]
`Connector.MySql`

**Comment by VitaliyMF** [comment]
I'm not sure that separate token will help in this case; for example first result for "pdf" (https://www.nuget.org/packages?q=pdf) is "iTextSharp".
It seems latest nuget.org [uses Lucense.NET](https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Indexing/NuGetSearcherManager.cs) for indexing and searching most relevant packages - you can explore the code how they construct lucene query: https://github.com/NuGet/NuGet.Services.Metadata/blob/master/src/NuGet.Indexing/NuGetQuery.cs

All this means that it is a very little sense in renaming nuget package ID; instead of that you can improve presence in search results by:

- add <Title> to csproj with value that separates "mysql" keyword
- add more content to <Description> (use "mysql" several times). 
- use <PackageReleaseNotes> with some useful content that also contains "mysql" keyword
- add more tags (for example, "MySql.Data" repeats "MySql" tag 3 times! They are cheaters without doubt hehe)

**Comment by caleblloyd** [comment]
I personally find nuget's search algorithms very poor so I use Google and/or GitHub to discover C# packages. I fell like a lot of the C# community may do this as well.

There are probably numerous references to MySqlConnector across stack overflow and other places on the internet. The BC breakage does not seem worth it, just to appease nuget's current search algorithm.

Nuget just got a facelift so there may be more improvements in the works. Is there an open way to request a better search algorithm from nuget?

**Comment by bgrainger** [comment]
> * add <Title> to csproj with value that separates "mysql" keyword
> * add more content to (use "mysql" several times).
> * use with some useful content that also contains "mysql" keyword

I tried some of these in the latest release; see changes in a45427e741ca644b9a3fe7c1b7f5301a64b96e51. It didn't seem to improve the ranking.

**Comment by VitaliyMF** [comment]
> I tried some of these in the latest release; see changes in a45427e. It didn't seem to improve the ranking.

Content is still too short and "mysql" repeated several times might help. Also, have you tried to add "mysql" tag several times like in "MySql.Data"? I agree that currently nuget search is rather irrelevant.

**Comment by bgrainger** [comment]
Not worth breaking compatibility to try to "game" the current NuGet search rankings.
