### ISSUE TITLE
.HasRows - Doesn't change to false on 28.2 driver - Watch Video

### ISSUE THREAD

**Issue by Topcoder01** [mysql-net/MySqlConnector#363]
Watch the video..

https://youtu.be/XpV4HHKpuOk

**Comment by bgrainger** [comment]
This is by design.

`DbDataReader.HasRows` is [documented as returning](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.hasrows?view=netframework-4.7.1#System_Data_Common_DbDataReader_HasRows)

> `true` if the DbDataReader contains one or more rows; otherwise `false`.

Its value does not change as rows are read; i.e., it does not indicate if there are more rows to read.

To check if there are more rows, examine the return value of [`Read`](https://docs.microsoft.com/en-us/dotnet/api/system.data.common.dbdatareader.read?view=netframework-4.7.1) (or `ReadAsync`), e.g.,

```
While oDataReader.Read()
    iC_ID = oDataReader("c_id")
End While
```

**Comment by bgrainger** [comment]
(The buggy behaviour was fixed in #327.)

**Comment by bgrainger** [comment]
As per the comment on #327, this was actually changed to behave the same as the normal MySQL driver. These tests verify that this library performs the same as Connector/NET: https://github.com/mysql-net/MySqlConnector/blob/518513bc4865a89ebfc365afd5f9c1bc1cf2b260/tests/SideBySide/QueryTests.cs#L782-L815

**Comment by Topcoder01** [comment]
You're right, absolutely, I scanned all my code and I didn't have this condition anywhere else. Thanks for pointing it out..  Saved me a big headache.
