### ISSUE TITLE
Is it able to support DbProviderFactories configuration similar to Mysql.Data?

### ISSUE THREAD

**Issue by ghd258** [mysql-net/MySqlConnector#525]
Is it able to support DbProviderFactories configuration similar to Mysql.Data?

`<DbProviderFactories>
      <remove invariant="MySql.Data.MySqlClient" />
      <add name="MySQL Data Provider" invariant="MySql.Data.MySqlClient" description=".Net Framework Data Provider for MySQL" type="MySql.Data.MySqlClient.MySqlClientFactory, MySql.Data, Version=6.9.12.0, Culture=neutral, PublicKeyToken=c5687fc88969c44d" />
    </DbProviderFactories>`

**Comment by bgrainger** [comment]
Is this element in the system-wide `machine.config`, or a per-application `app.config` or `web.config`?

**Comment by ghd258** [comment]
There are, if supported, how MySqlConnector should write this configuration.

**Comment by ghd258** [comment]
![qq 20180705151629](https://user-images.githubusercontent.com/4811375/42307877-7bbcb686-8066-11e8-871a-107ca3615537.jpg)

**Comment by bgrainger** [comment]
From my reading at [Obtaining a DbProviderFactory](https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/obtaining-a-dbproviderfactory), it appears that the provider has to be registered in the (system-wide) `machine.config`. (This probably also implies that it must be installed in the GAC.)

This is not the intended use of MySqlConnector, which is designed as an app-local package. And since `DbProviderFactories` isn't in `netstandard2.0`, it seems like Microsoft is trying to deprecate this approach.

It may be possible to manually install MySqlConnector in the GAC and edit your `machine.config` by hand, but that won't be supported "out of the box" by this library. (Doing so would require an installer that elevates to edit those files.) 

MySqlConnector _does_ provide a `MySql.Data.MySqlClient.MySqlClientFactory`, so if all you need is a `DbProviderFactory` instance, that's already done.

**Comment by bgrainger** [comment]
Yes, you can use MySqlConnector with `DbProviderFactories` (on a .NET Framework project) by adding the following XML to your app.config or web.config:

```xml
<system.data>
	<DbProviderFactories>
		<add name="MySqlConnector" invariant="MySqlConnector" description="Async MySQL ADO.NET Connector" type="MySql.Data.MySqlClient.MySqlClientFactory, MySqlConnector, Version=0.42.2.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92" />
	</DbProviderFactories>
</system.data>
```

Once you do this, it will be available via `var factory = DbProviderFactories.GetFactory("MySqlConnector");`.

You will need to keep the version number updated every time you update the NuGet package.

**Comment by clabnet** [comment]
I have :
- installed MySqlConnector 0.51.1 with NuGet into my class .NET 4.6.1 project
- added this code into App.config

> ` <system.data>
>     <DbProviderFactories>
>       <remove invariant="MySqlConnector" />
>       <add name="MySqlConnector"
>            invariant="MySqlConnector"
>            description="Async MySQL ADO.NET Connector"
>            type="MySql.Data.MySqlClient.MySqlClientFactory, MySqlConnector, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92" />
>     </DbProviderFactories>
>   </system.data>`

(I have installed also into my **machine.config** the same DbProviderFactories)

The error is caused when I try to 
`DbProviderFactories.GetFactory(ProviderName) `
where ProviderName is MySqlConnector.

Please see also https://github.com/mysql-net/MySqlConnector/issues/526
