### ISSUE TITLE
Enum's in parameters don't match exact

### ISSUE THREAD

**Issue by PeterHagen** [mysql-net/MySqlConnector#532]
I updated my code to the latest 0.42.3, and have some issues with enum fields, which didn't happen before. I pass an enum value in a parameter, which queries a mysql enum field. Amongst others, I have a member ListArticle and a member List. It seems that when I query with the List value, it also matches ListArticle. After I changed my query parameter to a string, it didn't match both, but just the correct record. Could it be that a wildcard is being used on the value?

**Comment by bgrainger** [comment]
Please provide an example table schema and sample code that reproduces the problem.

**Comment by bgrainger** [comment]
For example, the following schema and code works as expected for me:

```sql
drop table if exists issue532;
create table issue532(
	rowid integer not null primary key auto_increment,
	kind enum('Article', 'List', 'ListArticle') not null
);

insert into issue532(kind)
values('List'), ('List'), ('ListArticle'), ('Article'), ('ListArticle'), ('Article');
```

```csharp
enum Test
{
	None,
	Article,
	List,
	ListArticle,
}

using (var connection = new MySqlConnection(csb.ConnectionString))
{
	connection.Open();
	using (var command = new MySqlCommand(@"select rowid, kind from issue532 where kind = @Kind", connection))
	{
		// use any of the following methods to add the parameter
		command.Parameters.AddWithValue("@Kind", "List");
		command.Parameters.AddWithValue("@Kind", Test.List).DbType = DbType.String;
		command.Parameters.AddWithValue("@Kind", Test.List);
		
		using (var reader = command.ExecuteReader())
		{
			while (reader.Read())
			{
				Console.WriteLine("{0} {1}", reader.GetValue(0), reader.GetValue(1));
			}
		}
	}
}
```

**Comment by bgrainger** [comment]
MySQL `ENUM` values [start at 1](https://dev.mysql.com/doc/refman/8.0/en/enum.html#enum-literals), but `NodeState.Draft` has the integer value 0.

Because the type of the command parameter is not `DbType.String`, it is sent as a numeric value, i.e., 0. MySQL Server rejects that as invalid data (with a confusing message).

There are several alternate approaches you could use:

#### Send the value as a string

```csharp
command.Parameters.AddWithValue("?par0", NodeState.Draft).DbType = DbType.String;
// or
command.Parameters.AddWithValue("?par0", NodeState.Draft.ToString());
// or
command.Parameters.AddWithValue("?par0", "Draft");
```

#### Align the C# enum with MySQL

```csharp
public enum NodeState
{
    Draft = 1,
    Publish = 2,
    Deleted = 3,
    Pending = 4
}
```

This is probably less recommended as `default(NodeState)` is still valid C# but doesn't correspond to any allowed MySQL value.

#### Don't use a MySQL enum

Just declare the column as `TINYINT` and let MySqlConnector map the integer to/from `NodeState`. Downsides: you always have to use C# to translate the value; you can't `SELECT state FROM cms_nodes` and get the human-readable value.

**Comment by PeterHagen** [comment]
Before 0.42.3 it worked perfectly and as string, not a number. There is no numeric relation between the mysql enum and the enum in my code, and it was always matched as a string. Has this been changed in the connector? I used this code already for a long time, until I updated the nuget package last week.

**Comment by bgrainger** [comment]
What version did you upgrade from?

**Comment by bgrainger** [comment]
The only recent change I can think of is #459 (in 0.37.1), but that _added_ serialization as a string for enum values.

**Comment by PeterHagen** [comment]
Last week I updated from 0.40.4. I'll revert back to this one and test it

**Comment by PeterHagen** [comment]
Ok, Murphy's law... after switching to 0.40.4 and back to 0.42.3, I can't reproduce the issue at the moment. Not sure what is different now. Sorry, better close the issue till I figure it out.
