### ISSUE TITLE
Clearing the connection pool for failover scenarios

### ISSUE THREAD

**Issue by coddo** [mysql-net/MySqlConnector#582]
Hello,

This is more of a question than an actual issue.

We have a database cluster with 1 writer and n readers managed through AWS RDS, so we have only 2 connection strings, while load balancing on the readers is done by AWS directly.

When doing an upgrade to the cluster, at some point the writer node gets shut down and one of the readers takes its place (classic failover). The connector usually caches the IPs of each node behind the scenes, so when the failover happens, the connector still tries to execute write operations on the cached IP, which is now a reader node.

We have adapted our access layer to catch this kind of error (readonly exception) and we use the [ClearPoolAsync](https://dev.mysql.com/doc/dev/connector-net/6.10/html/Overload_MySql_Data_MySqlClient_MySqlConnection_ClearPoolAsync.htm) method to completely reset the connections.

I don't see this method implemented in the library. Are there any plans to implement something similar or is there another way to solve such an issue with what is currently offered by the MySqlConnector.

We were thinking of switching over from MySql.Data, but this might end up being a blocker.

**Comment by bgrainger** [comment]
A variety of overloads of `ClearPoolAsync` are supported and implemented here:

https://github.com/mysql-net/MySqlConnector/blob/73c4f4cda5d3d36255eda411580883a7d8a33d85/src/MySqlConnector/MySql.Data.MySqlClient/MySqlConnection.cs#L225-L230

The key difference from Connector/NET is that they are `static` methods that take the pool to clear, rather than being instance methods that (redundantly) also take the connection to operate on. (This is missing from [the migration docs](https://mysql-net.github.io/MySqlConnector/tutorials/migrating-from-connector-net/#mysqlconnection), sorry.)

> or is there another way to solve such an issue

I can't think of one. As long as you're using connection pooling, the physical network connections are getting cached, so there will be open sessions in the "write" connection pool to a server that no longer accepts writes. Clearing the pool seems like the only way to resolve this.

**Comment by bgrainger** [comment]
(See #46 for previous discussion of the `ClearPool(Async)` API design.)
