### ISSUE TITLE
Cannot commit transaction more than once

### ISSUE THREAD

**Issue by kwaazaar** [mysql-net/MySqlConnector#61]
Wrong description, but when committing a transaction, the SqlTransaction's Connection-property turns null. I depend on this behavior (perhaps I shouldn't), but for this library, the connection is not nulled on the transaction. Maybe this is something you would want to change to mimic the SqlTransactions' behaviour more.

**Comment by bgrainger** [comment]
I'll need to check if MySql.Data implements this behaviour; if it doesn't, this would be a potentially-breaking change for users switching from that MySQL provider to this library.

Additionally, clearing the connection when the transaction is committed isn't an obviously documented behaviour of `DbTransaction.Connection` or `IDbTransaction.Connection`, so it's not clear that this is a required or standard part of ADO.NET.

I'll investigate, but my initial inclination is (for better or worse) to clone `MySqlTransaction`'s behaviour here rather than `SqlTransaction`. The right solution might be to track (in your calling code) whether you've called `Commit` (and/or `Rollback`?) or not.

**Comment by bgrainger** [comment]
Interestingly, this behaviour *is* documented for [`SqlTransaction.Connection`](https://msdn.microsoft.com/en-us/library/system.data.sqlclient.sqltransaction.connection.aspx):

> Gets the SqlConnection object associated with the transaction, or `null` if the transaction is no longer valid.

But it's not documented as such on the base class or the interface.

**Comment by bgrainger** [comment]
Npgsql [appears to follow](https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/NpgsqlTransaction.cs#L55) the SqlTransaction model.

**Comment by bgrainger** [comment]
I checked this with AdoNet.Specification.Tests (https://github.com/mysql-net/AdoNetApiTest) and only Connector/NET doesn't clear `DbTransaction.Connection` when a transaction is committed (or rolled back).

![image](https://user-images.githubusercontent.com/188129/34465595-9583501a-ee68-11e7-8375-87e73261f388.png)

**Comment by bgrainger** [comment]
Fixed in [0.34.0](https://github.com/mysql-net/MySqlConnector/releases/tag/0.34.0).
