### ISSUE TITLE
Too Many "Change User" in connection

### ISSUE THREAD

**Issue by ShiningRush** [mysql-net/MySqlConnector#627]
Hi，
Our project use MySqlConnector to connect mysql instance of cloud,
then we find  that there are too many db operation "Change User" in logs,  and it is very cost time.

![image](https://user-images.githubusercontent.com/24238012/55317998-488bc500-54a4-11e9-9a1a-f65aaf312097.png)

Some times it will cause timeout in opening connection.

What cause the "Change User" operation and how to avoid it ?
any helps is appreciated.

**Comment by bgrainger** [comment]
What is your database server and version?

"Change user" (`COM_CHANGE_USER`) is used when retrieving a connection from the connection pool (to reset it back to a known good state) on MySQL Server v5.6.x and earlier.

If you're using MariaDB, make sure you're using MySqlConnector v0.50.0 or later: #613.

It is strongly recommended that you reset the connection so that server variables are reset, user-defined variables are cleared, temp tables are removed, etc. However, if you must disable this feature for performance reasons, you can set `ConnectionReset=false` in your connection string.
