### ISSUE TITLE
Failed to load provider `MySqlConnector` - Failed to find or load the registered .Net Framework Data Provider

### ISSUE THREAD

**Issue by clabnet** [mysql-net/MySqlConnector#629]
I have :
- installed MySqlConnector 0.51.1 with NuGet into my class .NET 4.6.1 project
- added this code into App.config

> ` <system.data>
>     <DbProviderFactories>
>       <remove invariant="MySqlConnector" />
>       <add name="MySqlConnector"
>            invariant="MySqlConnector"
>            description="Async MySQL ADO.NET Connector"
>            type="MySql.Data.MySqlClient.MySqlClientFactory, MySqlConnector, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92" />
>     </DbProviderFactories>
>   </system.data>`

(I have installed also into my **machine.config** the same DbProviderFactories)

The error is caused when I try to 
`DbProviderFactories.GetFactory(ProviderName) `
where ProviderName is MySqlConnector.

Please see also https://github.com/mysql-net/MySqlConnector/issues/526

_Originally posted by @clabnet in https://github.com/mysql-net/MySqlConnector/issues/525#issuecomment-480886146_

**Comment by bgrainger** [comment]
I created a simple WinForms .NET 4.6.1 application, added the App.config section, and the following lines of code functioned as expected:

```csharp
var provider = DbProviderFactories.GetFactory("MySqlConnector");
MessageBox.Show(provider.ToString());
```

Please provide a link to a standalone repro that demonstrates the problem.

**Comment by clabnet** [comment]
@bgrainger 
I repeated yout simple test but I have same issue. I use VS.NET 2017,  latest patch 15.9.11.
I think can be a local problem of my machine, but I don't know where is it.
Here a temporary link to my test project: https://takeafile.com/?f=nonejoyuru
Thanks

**Comment by bgrainger** [comment]
> Error: It seems the sender user has closed the browser.

Can you just publish it as a gist or a GitHub repo (or possibly https://send.firefox.com/)?

**Comment by bgrainger** [comment]
Your example project is a class library, so the app.config in the project has no effect. The DLL is being loaded by UserControlTestContainer.exe, which has no `<system.data>` section in its app.config.

(I _think_ machine.config should work but there may x86 vs x64 issues depending on the bitness of the hosting application. I also don't recommend making machine-wide changes, as it makes deployment etc. more difficult.)

Since your project has a direct reference to MySqlConnector, the simplest workaround might just be replacing `DbProviderFactories.GetFactory("MySqlConnector")` with `MySqlClientFactory.Instance`.
