### ISSUE TITLE
Support for delimiter statement

### ISSUE THREAD

**Issue by sl2man** [mysql-net/MySqlConnector#645]
Is there any way to execute statements that require changing of default delimiter? For example, how to execute script that creates function that uses ";" in it's code?
Simple usage of MySqlCommand with text like "delimiter $$" throws an exception.

**Comment by bgrainger** [comment]
`DELIMITER $$` is unnecessary with MySqlConnector because it doesn't try to break SQL strings into individual statements and execute them separately. That directive is only for clients who need to parse SQL in a naive way.

It should "just work" to create a `MySqlCommand` with your entire script and then call `ExecuteNonQuery()`. For example, see the tests here, that demonstrate creating a function that contains `;` in the code: https://github.com/mysql-net/MySqlConnector/blob/ffb45f3303bc98c4e59ee715390b6fa21064ab29/tests/SideBySide/StoredProcedureFixture.cs#L17-L24

(That uses `Execute` from [Dapper](https://github.com/StackExchange/Dapper) but the principle is the same.)

**Comment by LeonardoDaLuz** [comment]
Yes, it is necessary, if I want to run a .sql to assemble the entire schema I can't.

**Comment by bgrainger** [comment]
> It should "just work" to create a `MySqlCommand` with your entire script and then call `ExecuteNonQuery()`.

Can you use this recommendation from the comment above?
