### ISSUE TITLE
在 Connection 被 Open 之前，获取 ConnectionTimeout 出现异常

### ISSUE THREAD

**Issue by XiaoHeitu** [mysql-net/MySqlConnector#669]
在 Connection 被 Open 之前，获取 ConnectionTimeout 出现异常
![QQ截图20190715161459](https://user-images.githubusercontent.com/38452227/61203117-11bc8080-a71c-11e9-9715-a923cab45672.png)

**Comment by XiaoHeitu** [comment]
不只是ConnectionTimeout，用到m_connectionSettings的属性都会出现异常，因为Connection在没有Open之前，m_connectionSettings 是 null。

**Comment by bgrainger** [comment]
Most usages of `m_connectionSettings` have been audited and will only be called when the connection is open; accessing `m_connectionSettings` directly is a deliberate optimisation.

Some problems were found and fixed when adding C# 8.0 nullable annotations to the codebase (on a test branch); apparently this one was missed.

**Comment by XiaoHeitu** [comment]
嗯。。m_connectionSettings 为 null 只是显现，但不是主要问题，主要问题在于，m_connectionSettings里面有一些属性是可以直接从 ConnectionString 中解析出来，从正常逻辑来说这些属性不应该等待Connection被Open 之后再被使用。

**Comment by bgrainger** [comment]
I audited all usages of `m_connectionSettings` and found one more problem: calling `MySqlConnection.EnlistTransaction` when the transaction was closed would throw `NullReferenceException` when it should have thrown `InvalidOperationException`.

Since this is already an invalid operation, it doesn't matter that much, but I've fixed the code to throw the right exception: a3fb4c0b0e6f620445652d11abbac559f7de25af

All other usages of `m_connectionSettings` should be OK. Please do let me know if you see/find any specific problems.
