### ISSUE TITLE
Question: Is there any plan for the next stable release?

### ISSUE THREAD

**Issue by nhathongly** [mysql-net/MySqlConnector#683]
May I know when MySqlConnector-0.57.0 will be released?
And thanks for your effort to fix issues so quickly!

**Comment by bgrainger** [comment]
This release will take a little longer, since there are breaking changes that affect consumers, e.g., https://github.com/mysql-net/MySqlConnector/issues/642#issuecomment-508099326.

The beta versions undergo the same testing as a regular stable release, so if you're aware of the [changes in this version](https://mysqlconnector.net/overview/version-history/), please install [the latest beta](https://www.nuget.org/packages/MySqlConnector/0.57.0-beta8) and provide feedback about any problems you encounter.

**Comment by bgrainger** [comment]
0.57.0 (stable) is now available on NuGet.
