### ISSUE TITLE
Project is using C# 8 which isn't available to many people yet

### ISSUE THREAD

**Issue by phillijw** [mysql-net/MySqlConnector#689]
I use Jetbrains Rider on mac so I am limited in which IDE choices I have. C# 8 is not an option for me yet with this IDE so I am unable to build the projects that use the new C# 8 features. Just something to keep in mind I guess since I doubt anybody would bother undoing those changes to make them 7.3 compatible.

**Comment by bgrainger** [comment]
I know that C# 8 requires installing a preview version of .NET Core 3.0, which reduces the number of people who can build the library; however, that was already being added as a dependency so MySqlConnector could be implementing upcoming .NET Core 3.0 (#642) and .NET 5 (#650) APIs before those frameworks were released.

Is using VS Code (with a preview version of .NET Core 3.0 SDK) a viable workaround for you (until Rider has C# 8 support)?

(Note that C# 8 features that require `netstandard2.1` won't be used because the library needs to remain compatible with .NET 4.5, which won't support `netstandard2.1`.)

**Comment by phillijw** [comment]
Using VS Code is a good suggestion. I can try that. Thanks

**Comment by caleblloyd** [comment]
It is possible to use .NET Core 3.0 Preview with Rider, I have been doing it.  You just need to install the SDK and point Rider to it in "Toolset and Build" menu:

SDK: https://dotnet.microsoft.com/download/dotnet-core/3.0
Picture of where to change setting: https://stackoverflow.com/a/57113401/1419658
