### ISSUE TITLE
Wrong conversion for Tinyint type

### ISSUE THREAD

**Issue by daikoz** [mysql-net/MySqlConnector#738]
Hi,

Mariadb "tinytint unsigned" is converted to System.Byte => OK
But:
Mariadb "tinyint" is converted to System.Boolean => WRONG
tinyint have signed range is -128 to 127. System.Boolean is only true or false. We lost information.
tinyint should be convert to sbyte (range -128 to 127):

https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(sbyte_CSharpKeyword)%3Bk(DevLang-csharp)%26rd%3Dtrue

But sbyte is not CLS compliant. We should perhaps modify to int16 ?

**Comment by bgrainger** [comment]
This is almost certainly by design (but can be investigated more if you provide a full example of how to reproduce the problem).

`TINYINT(1)` is an alias for `BOOL` and will be returned as `System.Boolean`. Don't explicitly specify `TINYINT(1)` unless you want a `Boolean` column; use `TINYINT` (or `TINYINT(3)` instead).

Alternatively, to disable this conversion, set `TreatTinyAsBoolean=False` in your connection string.

> But sbyte is not CLS compliant. We should perhaps modify to int16 ?

This library doesn't aim to be CLS-compliant. You can call `MySqlDataReader.GetInt16` or `(short) reader.GetValue()` to widen to `Int16` if necessary.
