### ISSUE TITLE
Request: support arrays in SQL parameters

### ISSUE THREAD

**Issue by rmunn** [mysql-net/MySqlConnector#751]
Today I wanted to write `SELECT * FROM users WHERE username IN @usernames`, with `@usernames` being an array of strings, e.g.:

```csharp
var usernames = new string[] { "foo", "bar", "baz" };
cmd.Parameters.AddWithValue("usernames", usernames);
```

But this throws `System.NotSupportedException: Parameter type String[] (DbType: String) not currently supported. Value: System.String[]` when I try it. A quick look at the code tells me that indeed, I can't pass an array as an SQL parameter.

Is there any way this could be implemented? I can work around the lack of array parameters by looping through my string array and constructing one SELECT statement per username, so I'm doing the equivalent of:

```plaintext
SELECT * FROM users WHERE username = 'foo';
SELECT * FROM users WHERE username = 'bar';
SELECT * FROM users WHERE username = 'baz';
```

But this is obviously inefficient for a large list. I'd much rather do this in one SELECT statement with an IN selector. Would that be an easy feature to add, or would it be hard?

**Comment by bgrainger** [comment]
I'd recommend using an existing library that can already do this. Dapper has built-in support for list/IEnumerable parameters: https://github.com/StackExchange/Dapper#list-support.

It should be easy to add Dapper to your project and change individual queries (that need array/list support) to use `.Query`.

**Comment by jayrowe** [comment]
Is there any reason not to implement this directly in the connector? I know that Dapper does this, but the implementation is a little silly from what I've seen. 

From what I can tell, you call Dapper with sql like:

`SELECT * FROM TableName WHERE ColumnName IN @values;`

Note the syntax is `IN @values`, not `IN (@values)`.

Dapper does some string manipulation to produce:

`SELECT * FROM TableName WHERE ColumnName IN (@values1,@values2,@values3,@values4,@values5,@values6,@values7,@values8,@values9,@values10,@values11,@values12,@values13);`

Dapper also adds a parameter for each item in the collection.

When I look at the traffic over the wire it looks something like:

`SELECT * FROM TableName WHERE ColumnName IN (1,2,3,4,5,6,7,8,9,10,11,12,13);`

Unless I'm missing something, that means that the connector had to parse the sql and find (and replace) all of the parameters. There is basically a bunch of work that Dapper is doing that needs to be redone to send it over the wire.

I'm also not sure if Dapper supports syntax like this, either:

`SELECT * FROM TableName WHERE (Column1, Column2) IN ((1,2),(3,4),...)`

I think it would probably be trivial to support this here.

**Comment by bgrainger** [comment]
Because MySQL doesn't support array parameters (for prepared statements), this shouldn't be implemented inside MySqlConnector.

A solution that rewrites the SQL with inline text could be implemented as a third-party library that works with any ADO.NET provider; it doesn't need to be a MySqlConnector feature.

**Comment by jayrowe** [comment]
I'd say it's reasonable to make this easy for a common use case with the caveat that it just doesn't work for prepared statements. At the end of the day there isn't a reasonable way to prepare the statement because of limitation in mysql, not a limitation in the client. If you tried to do it, it would fail when you tried to execute the PREPARE command (invalid syntax caused by missing parens).

The Dapper method seems to be the only way that's provider agnostic absent this support and frankly, it's silly to construct a giant sql string and a bunch of parameter objects just to have the next step undo that work. The workaround is to construct sql strings manually, which I can write my own library to do but is more of a maintenance headache for a relatively simple use case.
