### ISSUE TITLE
Logging full query with values

### ISSUE THREAD

**Issue by jmihalich** [mysql-net/MySqlConnector#754]
Hi,

    I'm using this library along with the NLog connector to log database info. (.Net Core 3.1).  Everything is working great, but you don't seem to be logging the full un-tokenized string.  ie:  If i have a query:
select companyName from company where companyId = @companyId

   when i execute the query (with MySqlConnector log settings set to Debug), all i get is this line in the log:

`2019-12-27 14:58:18,525 [DEBUG] [4] MySqlConnector.Logging.LoggerExtensions.Debug - Session1.5 Preparing command payload; CommandText: select companyName from company where companyId = @CompanyId`

That's not really helpful when the query is not returning something it shouldn't be.  It would be great if you could log the full statement after the tokens are replaced like:

`2019-12-27 14:58:18,525 [DEBUG] [4] MySqlConnector.Logging.LoggerExtensions.Debug - Session1.5 Preparing command payload; CommandText: select companyName from company where companyId = 12345`

   Is there a way to get this to log and i'm just missing it?  If not, can you add this feature at some point in the future?  And is there a way for me to pull the full query string from the MySqlCommand object so i can log it myself?

Thanks,
Joe

**Comment by bgrainger** [comment]
This is currently by design, to avoid logging potentially-sensitive information (e.g., email addresses, (hashed) passwords, account numbers, etc.). 

There's also a practical consideration: long strings or large BLOBs might make the log statements dozens of megabytes if `@paramValue` were replaced with the actual value. Additionally, BLOBs could contain arbitrary binary data that can't be interpreted as UTF-8 or any other Unicode encoding.

> And is there a way for me to pull the full query string from the MySqlCommand object so i can log it myself?

Not really; as above, it never exists as a `String`, but as a binary blob (that's not necessarily UTF-8) that's going to be sent to the server.

If you need to know parameter values, I would suggest logging something like:

```csharp
$"SQL: {command.CommandText}; Parameters: {string.Join(", ", command.Parameters.Select(x => x.Value.ToString()))}"
```

**Comment by jmihalich** [comment]
Yeah, that was my last resort option to do it that way.   

I'm a java dude moving over to .net core land, and i've been using log4jdbc which logs a crap ton of stuff depending on what you turn on, like the full statement, timing info, etc.  So was just looking for similar functionality.

Thanks for the info and for responding so fast. Happy holidays.

Joe
