### ISSUE TITLE
Remove 'sealed' from MySqlCommand and consider virtual members

### ISSUE THREAD

**Issue by udlose** [mysql-net/MySqlConnector#777]
As of the latest version of MySqlConnector (currently v 0.62), the `MySqlCommand` class is `sealed` and has no `virtual` members.  This doesn't allow me to extend or override any behavior.  For example, I want to hook up tracing for all db commands so I want a single place to encapsulate that functionality.  So, I planned on extending the `MySqlCommand` class to override its behavior to wrap calls to the db with APM tracing.

What I'm forced to do is go to each call location where the `MySqlCommand` is *used* and add tracing around those methods.  This breaks the SRP Principle and makes the code not easily maintainable.

Please consider allowing for this class to be extended.

**Comment by bgrainger** [comment]
This would be better solved with [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance).

It's fairly simple to create an ADO.NET wrapper that completely encapsulates another ADO.NET library; here's an example where I built one: https://github.com/Faithlife/FaithlifeTracing/tree/master/src/Faithlife.Tracing.Data

One benefit of this is that it now works with _any_ ADO.NET library (and allows them all to be traced), rather than being MySqlConnector-specific.

It also avoids SRP violations in MySqlCommand (which would have to serve double-duty as a class designed to expose a public interface to create commands, _and_ a class designed for arbitrary inheritance).

**Comment by udlose** [comment]
@bgrainger good idea. I guess I can consider the Decorator Pattern.  I think the old "OOP-guy" in me kicked in when I filed this Issue.  My apologies for the wasted bits :)
