### ISSUE TITLE
tinyint doesn't convert to bool on Debian

### ISSUE THREAD

**Issue by daikoz** [mysql-net/MySqlConnector#784]
Hi,

I develop the tool [SQL Wrapper ](https://github.com/daikoz/SQLWrapper) to generate automatically a wrapper form request with mysql/mariadb to C# code.

When I create a mariadb table with 1 column with type tinyint.

Follow a sample:
```C#
            using MySqlConnection db = new MySqlConnection("XXXXXX");
            using MySqlCommand sqlCmd = new MySqlCommand
            {
                Connection = db,
                CommandText = @"SELECT IsValue FROM TempTable LIMIT 1", // IsValue is TINYINT
            };
     
            db.Open();
            object result = sqlCmd.ExecuteScalar();

            // On Windows: System.Boolean => OK
	    // On debian:  System.SByte   => KO	    
            Console.WriteLine(result.GetType().ToString());
```

On Windows, the type returned is **Boolean** => **OK**
On Linux, the type returned is **SByte** => **KO**

Database is same on debian:
Server version: 10.3.22-MariaDB-0+deb10u1-log Debian 10

dotnet:  Version: 3.1.2

mysqlconnector: 0.62.0

**Comment by bgrainger** [comment]
https://github.com/mysql-net/MySqlConnector/blob/master/tests/SideBySide/DataTypes.cs has extensive tests of the data types returned by `GetValue` (which is then returned by `ExecuteScalar`). These tests are executed on each build on both Windows and Linux, and don't have platform-specific differences.

I suspect I'll need a much more detailed example in order to reproduce this.

**Comment by daikoz** [comment]
ok, it is an issue in my db linux. I define IsValue with TINYINT(4) instead of TINYINT(1) (=BOOL).
Thanks, I close issue
