### ISSUE TITLE
MySqlDataSourceEnumerator

### ISSUE THREAD

**Issue by rgarrison12345** [mysql-net/MySqlConnector#796]
System.Data.SqlClient and Microsoft.Data.SqlClient provide a way to see sql instances on the local network the application is executing from.  Can MySqlConnector provide a similar API?  DbDataSourceEnumerator is a part of System.Data.Common API.

**Comment by bgrainger** [comment]
I'm not aware of any mechanism by which MySQL Servers advertise their presence on a local network, that MySqlConnector could use to discover them. (If anyone knows, please add a pointer in a comment on this issue.)

**Comment by bgrainger** [comment]
I don't believe this is technically possible (but can reopen the issue if someone identifies a way to accomplish it).

I don't think `DnsSrv` (introduced in [Connector/NET 8.0.19](https://dev.mysql.com/doc/relnotes/connector-net/en/news-8-0-19.html)) is a solution, since it identifies a single pool of servers for a domain, not a way to discover multiple separate instances.
