### ISSUE TITLE
Production Ready And 100% Drop-in Replacement

### ISSUE THREAD

**Issue by investagrams** [mysql-net/MySqlConnector#806]
Hi,

We have just discovered this connector lately and it seems that it is a better version of the official mysql oracle .net connector. Currently we ware using the official mysql oracle .net connector v6.9.10 and we are planning to entirely switch to this connector, is this a production ready already? Like in production we are experiencing high traffic and several concurrent request at the same time, if we are gonna totally switch to this connector, would it be safe? What are some caveats? And is this a 100% replacement? Meaning we won't need to make any changes in our current  code base? We are just using the simple query like:

1. Open connection: 

```
MySqlConnection connection = new MySqlConnection(ConnectionString); 
Connection.Open();
```

2.  Running Query:

```
myCommand = new MySqlCommand(sql, (MySqlConnection)connection);
myCommand.Parameters.AddWithValue(Convert.ToString(pair.Key), pair.Value);
MySqlDataReader  ret = myCommand.ExecuteReader(); or int ret = myCommand.ExecuteNonQuery();
```

3. Using Stored procs:

```
 MySqlCommand cmd = new MySqlCommand("XXXXXX", (MySqlConnection)Connection);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Transaction = (MySqlTransaction)Transaction;

                cmd.Parameters.AddWithValue("param1", x);
                cmd.Parameters["param1"].Direction = ParameterDirection.Input;

                cmd.Parameters.AddWithValue("param2", y);
                cmd.Parameters["param2"].Direction = ParameterDirection.Input;

                MySqlDataReader ret = cmd.ExecuteReader();
```

4. When retrieving the column / row values:

```
MySqlDataReader ret = myCommand.ExecuteReader();

                while (ret.Read())
                {
long x = ret.GetInt64(ordinal)
                }
```

Is there anything we should consider, or do we need to make big changes to our current code base? We have so many tables and database already.

**Comment by bgrainger** [comment]
> is this a production ready already? Like in production we are experiencing high traffic and several concurrent request at the same time, if we are are totally switch to this connector, would be safe?

Yes, this connector is production-ready, and already used by many sites.

It's stress-tested in the TechEmpower Framework Benchmarks and can serve over 200,000 requests/second: https://www.techempower.com/benchmarks/#section=data-r18&hw=ph&test=fortune

> What are some caveats? And is this a 100% replacement? Meaning we won't need to make any changes in our current code base?

Generally, it's a 100% compatible drop-in replacement. There are a few minor changes from MySql.Data that are covered here: https://mysqlconnector.net/tutorials/migrating-from-connector-net/

Some changes can be turned off with a connection string option. Others will require code changes.

Looking at your code, no changes should be necessary to switch to MySqlConnector. However, I would strongly recommend disposing all database objects you create; this will clean up server resources and make the code more efficient. The best way to do this is with a `using` statement:

```csharp
using (var ret = myCommand.ExecuteReader())
{
    while (ret.Read())
    {
        // do something
    }
}
```

**Comment by investagrams** [comment]
> The best way to do this is with a using statement:

Oh, right now are not not closing our MySqlDataReader, we just close our connection by calling Connection.Close(); in the finally part, since we wrap all our DB calls in a try catch with repeat, Thank you for your recommendation. Will it improve our current performance if we will gonna close the MySqlDataReader too? 

Also i have another question, in the current MySQL.Data, retrieving float, double or decimal data types from DB will contain trailing zeroes, for example, our database for decimal in MySQL DB is: DECIMAL(30,10), and the value is just 10.20, upon calling the ret.GetDecimal in c#, the value would be 10.2000000000 (it will contain the trailing zeroes), is there an easy way or optimal way to trim the trailing zeroes in this new MySqlConnector connector? We don't want to keep the trailing zeroes since it can lead up to the API response JSON where the data will have the trailing zeroes as well (more bandwidth consumption),

Another question, can we get the data of the column by using column name with safe checker of if the column is null? Just use the default value of the data type or return a nullable data type if the column is null. In the current MySQL.Data connector, if the column is null, it will throw an exception error, so we need to call the IsDBNull first and i think that has some overhead performance issue.

**Comment by bgrainger** [comment]
> Oh, right now are not not closing our MySqlDataReader, we just close our connection by calling Connection.Close(); in the finally part, since we wrap all our DB calls in a try catch with repeat, Thank you for your recommendation. Will it improve our current performance if we will gonna close the MySqlDataReader too?

You should be able to simplify your connection code by using `using (var connection = new MySqlConnection(ConnectionString)) { }`. This will automatically call `connection.Close()` at the end of the block, cleaning up the resources used by the DB connection. Yes, it should improve performance in MySql.Data to dispose your `MySqlDataReader` objects because they have finalizers. (MySqlConnector does not, which helps it be higher performance.)

> Also i have another question, in the current MySQL.Data, retrieving float, double or decimal data types from DB will contain trailing zeroes

I'm not sure about this right now.

> Another question, can we get the data of the column by using column name with safe checker of if the column is null? Just use the default value of the data type or return a nullable data type if the column is null. In the current MySQL.Data connector, if the column is null, it will throw an exception error, so we need to call the IsDBNull first and i think that has some overhead performance issue.

Calling `IsDBNull` has negligible performance overhead; the data is all in memory, so there's no extra round-trip to the server.

If you want to avoid the extra code for calling `IsDBNull`, then you could consider using a library like Dapper: https://github.com/StackExchange/Dapper/

It can convert DB NULLs to `string` or `int?` which can make working with the database easier. It's also very low overhead.

**Comment by investagrams** [comment]
Alright, one last question, we are using .net framework 4.7.2, is this fully compatible? Also, we can just get this library via nuget and just search for "MySqlConnector" right? We are planning to implement this library soon and totally drop the mysql.data (oracle). Thank you so much for this connector. I hope this will be maintained and improve as we move forward.

**Comment by bgrainger** [comment]
Yes, it's fully compatible with .NET Framework (4.5 and higher) and .NET Core.

Search for MySqlConnector on NuGet to install it.

**Comment by danielgindi** [comment]
@investagrams Try in first for a few days in a QA environment.

This connector is 100% production ready and a drop-in replacement, and it's much more production ready than Oracle in the sense that if a bug is found - it's fixed in a matter of days, not 10 years!

But it's not 100% compatible. You have to be a bit careful. I'll explain:
The Oracle connector is very "forgiving", in the sense that it's doing very wrong casts in some situations. If you have a code that by mistake calls `GetString` instead of `GetInt64`, oracle will cast the `Int64` to a string. This one won't. 

So this is a chance to also make sure your code is correct.

**Comment by investagrams** [comment]
@danielgindi Thanks! Will definitely try it first on our local / dev / QA env. 

Are there other things that we should consider aside from the one you mentioned?

**Comment by danielgindi** [comment]
@investagrams Not that I'm aware of. Connection strings are compatible, except features which are not required due to MySqlConnector doing things way better. 

Maybe one weirdness of `MySqlScript` not existing here at all. It's basically a client side tokenizer. But the new `MySqlCommand` actually supports multiple statements in one query, so for all cases that do not require the `DELIMITER $$` statement - you're fine!

**Comment by MarcoRossignoli** [comment]
My 2c if you need `MySqlScript`(useful for testing for intance, we have live prod with `MySqlConnector` but we use `MySqlScript` on tests) and you need to reference project with `MySqlConnector` follow this guide and use an alias for smooth move https://stackoverflow.com/a/52417185

**Comment by bgrainger** [comment]
For `MySqlScript`, watch issue #382.

**Comment by investagrams** [comment]
What do you exactly mean by MySqlScript ? Sorry, it seems that this term is new for us. Based on our code base, we don't use MySqlScript, we only use the following mysql related: MySqlConnection, DbConnection, DbTransaction, MySqlTransaction, MySqlException, MySqlDataReader, MySqlCommand 

and from MySqlDataReader, we are using the following method to retrieve values:
Example:

For datetime:

int ordinal = ret.GetOrdinal(columnName);

            if (ret.IsDBNull(ordinal))
            {
                return DateTimeConstant.LOW_VALUE;
            }
            else
            {
                DateTime result = ret.GetDateTime(ordinal);

                result = DateTime.SpecifyKind(result, DateTimeKind.Local);

                return result;
            }

or for string:

int ordinal = ret.GetOrdinal(columnName);

            if (ret.IsDBNull(ordinal))
            {
                return null;
            }
            else
            {
                return ret.GetString(ordinal);
            }

or for int:

int ordinal = ret.GetOrdinal(columnName);

            if (ret.IsDBNull(ordinal))
            {
                return 0;
            }
            else
            {
                return ret.GetInt32(ordinal);
            }


Also how does this library handle connection pooling? Is it already like built in in the library by default? OR is there any connection string that we need to explicitly set?  

This is our current connection string:
SERVER=localhost;DATABASE=xxxx;PORT=3306;USERID=xxxx;PASSWORD=xxxxPOOLING=true;DEFAULT COMMAND TIMEOUT=8;Connection Timeout=5;ProcedureCacheSize=1000;charset=utf8mb4;

**Comment by MarcoRossignoli** [comment]
@investagrams don't worry `MySqlScript` is useful only if you want to run scripts where you have `DELIMITER` statement.

**Comment by bgrainger** [comment]
> Based on our code base, we don't use MySqlScript, we only use the following mysql related: MySqlConnection, DbConnection, DbTransaction, MySqlTransaction, MySqlException, MySqlDataReader, MySqlCommand

All these are supported and will work as you expect.

> Also how does this library handle connection pooling? Is it already like built in in the library by default? OR is there any connection string that we need to explicitly set?

Yes, it's supported and on by default.

> This is our current connection string:
SERVER=localhost;DATABASE=xxxx;PORT=3306;USERID=xxxx;PASSWORD=xxxxPOOLING=true;DEFAULT COMMAND TIMEOUT=8;Connection Timeout=5;ProcedureCacheSize=1000;charset=utf8mb4;

You don't need `POOLING=true;` because that is the default. `ProcedureCacheSize` is unnecessary for MySqlConnector and you will need to remove it to avoid getting an error. `charset=utf8mb4` is already the default and can be removed if you want.

**Comment by investagrams** [comment]
@bgrainger hi, thank you for all the information. But would it be okay to keep the POOLING=true; and the charset=utf8mb4 in the connection string?

Also, how would mysqlconnector handle the ProcedureCacheSize  ? Is it on by default?

We have also noticed that we are using this "use procedure bodies=true;" in our connection string, shall we remove this?

**Comment by investagrams** [comment]
We are encountering some issue when trying to use MySqlDataReader.GetString(ordinal), this is the error message: Unable to cast object of type 'System.Int64' to type 'System.String'. We are using some sort of generic retrieval of column then parse later on to the right data type, that's why we are just using the GetString. What is the alternative way that we can use?

**Comment by bgrainger** [comment]
> But would it be okay to keep the POOLING=true; and the charset=utf8mb4 in the connection string?

Yes.

> Also, how would mysqlconnector handle the ProcedureCacheSize ? Is it on by default?
> 
> We have also noticed that we are using this "use procedure bodies=true;" in our connection string, shall we remove this?

Remove both of these; they're handled automatically.

> And oh i forgot, lastly we are using MySQL 5.7 and 5.6 as our Database server in our PROD, would this be okay right? No problem at all?

Yes, both of these are fine.

> We are encountering some issue when trying to use MySqlDataReader.GetString(ordinal), this is the error message: Unable to cast object of type 'System.Int64' to type 'System.String'. We are using some sort of generic retrieval of column then parse later on to the right data type, that's why we are just using the GetString. What is the alternative way that we can use?

This isn't supported by default because it's a common source of locale-specific bugs; see https://github.com/mysql-net/MySqlConnector/issues/406#issuecomment-491637841

If you have to do it (which I would _strongly_ advise against), simply change that to `GetVaue(ordinal).ToString()`.
