### ISSUE TITLE
Is there a possibility of notification ?

### ISSUE THREAD

**Issue by MaxenceLvl** [mysql-net/MySqlConnector#861]
Hello,

I work on project and I need to detect when data is updated on database. Is any posibility to notify my application from that ?

Best regards

**Comment by bgrainger** [comment]
See my previous answer here: https://github.com/mysql-net/MySqlConnector/issues/522#issuecomment-399457142

**Comment by MaxenceLvl** [comment]
It's the same way for .NET framework 4.7.1 and MariaDB ?

**Comment by bgrainger** [comment]
It's the same for MariaDB as far as I know. For example, this open issue implies that no notification support currently exists in the server: https://jira.mariadb.org/browse/MDEV-16590.

**Comment by MaxenceLvl** [comment]
So there is no implementation like MySqlDependency at this day in MySqlConnector.

**Comment by bgrainger** [comment]
That is correct.

**Comment by mguinness** [comment]
There's a possibility that should work in theory, but I haven't tried it.  [Rebus](https://github.com/rebus-org/Rebus) is a message bus for .NET that supports multiple transports including MySQL (that incidentally uses this library).

The idea would be that you would create a MySQL trigger to [insert message data directly](https://github.com/rebus-org/Rebus.MySql/blob/f6d3581f0d1c0436880099fec523ed37be8e39de/Rebus.MySql/MySql/Transport/MySqlTransport.cs#L372-L387) into the transport table created by Rebus and it would then be picked up by the listener which polls in the background.

The article [Simple Messaging Between Microservices with Rebus and Azure Storage Queues](https://markheath.net/post/rebus-azure-storage-queues) shows how to setup the receiver in the application.  Since it still uses polling it's not particularly performant but it would be ideal for slowly changing dimensions.

**Comment by bgrainger** [comment]
Another possibility could be writing a client for MySQL's replication protocol, then setting it up as a (row-based) replica. You could theoretically fire off events for specific tables or even individual rows.

That's currently outside the scope of this library.
