### ISSUE TITLE
Connector pooling together w/ EF Core AddDbContextPool

### ISSUE THREAD

**Issue by mqudsi** [mysql-net/MySqlConnector#917]
EF Core 2.0 added a framework-level database connection pool, activated via `AddDbContextPool(connectionString, ...)` in services setup. MySqlConnector has its own driver-level client-side connection pooling via the `Pooling=...` connection string parameter.

Presumably using both simultaneously sits somewhere within the spectrum of `[unnecessary, harmful]`, but I figured I'd ask here about the official recommendation as you're more privy to the internal implementation of the driver-side connection pooling than I am without digging in.

Also, as I'm sure I'm not the only one to go poking about documented (and undocumented) connection string parameters: might I suggest updating [the connection options document](https://mysqlconnector.net/connection-options/) with a brief note about `AddDbContextPool()` somewhere in the vicinity of the `Pooling` option?

While we're at it: if anyone from Pomelo is reading this, the `Pooling` defaults to `true` in the default MySqlConnector configuration - does Pomelo change that?

**Comment by bgrainger** [comment]
@lauxjpn This is more of a Pomelo question; any thoughts?

**Comment by lauxjpn** [comment]
@mqudsi The client-side connection pool of MySqlConnector and the `DbContext` connection pool of EF Core are two independent concepts. They can be combined however.

The MySqlConnector connection pool does what you would expect of a traditional database provider: It keep once opened connections open, to reuse them in upcoming connection requests to save the TCP connection establishing time, the initial MySQL handshake time, etc.

The `DbContext` pool of EF Core keeps already created `DbContext` instances in a pool, so it can reuse them. Before they are returned to the pool, the state of all services is reset, which includes the `IRelationalConnection` derived service, that is a wrapper around the `MySqlConnection` object. For the `IRelationalConnection` derived services, this means calling its `Dispose()` method and thereby closing the connection (see [RelationalConnection.IResettableService.ResetState()](https://github.com/dotnet/efcore/blob/03c1ba5275b11963ee1d05ad388ded2fda861c1b/src/EFCore.Relational/Storage/RelationalConnection.cs#L934-L1002)).
This can save some time for high performance scenarios, where many `DbContext` instances are used in a very short amount of time, that all do very little of actual work. When they all start to do more work, the advantage of using `AddDbContextPool()` vanishes quickly.

So for maximum performance, use `AddDbContextPool()` in conjunction with MySqlConnector's client-side connection pool, so that when the `IRelationalConnection` derived service gets reset, disposing the `MySqlConnection` object does not actually close the underlying connection/session, but returns it to the pool.

**Comment by mqudsi** [comment]
Thank you kindly for the explanation. Much appreciated!
