### ISSUE TITLE
Database Character Set and Collation become incorrect after reconnection.

### ISSUE THREAD

**Issue by IgorSipin** [mysql-net/MySqlConnector#926]
My MySql database has default characterset **utf8** and collation **utf8_unicode_ci**. It works correctly until I close the MySqlConnection and open it again. After that the chracterset and collation become **latin1** and **latin_swedish_ci** respectively which is incorrect.  
Following C# console app demonstrates the issue:  
```cs
using MySqlConnector;
using System;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var server = "<server name>";
            var database = "<database name>";
            var user = "<user name>";
            var pwd = "<user password>";
            using var conn = new MySqlConnection($"Server={server}.mysql.database.azure.com; Database={database}; Uid={user}@{server}; Pwd={pwd}; SslMode=Preferred; Allow User Variables=true; ");

            conn.Open();
            PrintCollation("Fresh connection:", conn);
            conn.Close();

            conn.Open();
            PrintCollation("Reopenned connection:", conn);
            conn.Close();
        }

        static void PrintCollation(String msg, MySqlConnection conn)
        {
            Console.WriteLine(msg);
            using var command = new MySqlCommand("select @@character_set_database, @@collation_database;", conn);
            using var reader = command.ExecuteReader();
            while (reader.Read())
            {
                for (int i = 0; i < reader.GetColumnSchema().Count; i++)
                    Console.WriteLine($"  {reader.GetColumnSchema()[i].ColumnName} = {reader.GetValue(i)}");
            }
        }
    }
}
```
The result:  
```
Fresh connection:
  @@character_set_database = utf8
  @@collation_database = utf8_unicode_ci
Reopenned connection:
  @@character_set_database = latin1
  @@collation_database = latin1_swedish_ci
```
Specifying `ConnectionReset=false;` in the connection string fixes the issue.

**Comment by bgrainger** [comment]
I'm not convinced that this is a MySqlConnector bug.

I think that, similar to https://bugs.mysql.com/bug.php?id=97633, the server is resetting the "server side of the connection to its default state", even though the client's initial handshake packet specifies both a character set and an initial database.

Per https://dev.mysql.com/doc/refman/5.7/en/charset-database.html:

> If there is no default database, the variables have the same value as the corresponding server-level system variables, `character_set_server` and `collation_server`.
> 
> To see the default character set and collation for a given database, use these statements:
> 
> `USE db_name;`
> `SELECT @@character_set_database, @@collation_database;`

If I do that in your test program (i.e., `new MySqlCommand($"use {database}; select @@character_set_database, @@collation_database;", conn);`) then I get the expected results.

Since the current database is otherwise set correctly on the connection, I'm not inclined to add `USE {DatabaseName};` to every reset connection request as a workaround for just this issue.

Other than the incorrect values for these variables, do you notice any broken behaviour?

I think the right next step is to file a bug with Oracle, but based on bug 97633 I'm not personally optimistic that it would be addressed.

**Comment by IgorSipin** [comment]
I've noticed no other broken behavior other then the incorrect charset and collation. 
You are right, "use <database>;" helps.
