### ISSUE TITLE
SchemaTable.ProviderType set to -1 for TINYINT(1) type

### ISSUE THREAD

**Issue by MaceWindu** [mysql-net/MySqlConnector#933]
I found inconsistency between MySql.Data and MySqlConnector in ProviderType reported by `DataReader.GetSchemaTable` API for `TINYINT(1)`/`BOOL` column and I think `MySql.Data` behavior is correct one in this case.

MySql.Data reports 1 (tinyint) as underlying type in `ProviderType` column:
![image](https://user-images.githubusercontent.com/1099238/105576753-48de0a00-5d75-11eb-8c3d-92a80367c449.png)

`MySqlConnector` reports it as -1 (mapped to custom BOOL type):
![image](https://user-images.githubusercontent.com/1099238/105576862-049f3980-5d76-11eb-80c6-15e003181e6c.png)

**Comment by bgrainger** [comment]
MySqlConnector makes this difference (at least internally) to distinguish `TINYINT(1)` (`Bool`) from `TINYINT` (`Byte`) (and to respect the `TreatTinyAsBoolean` connection string option).

Is this causing a problem? Or are you arguing that since MySQL Server itself uses `TINYINT`, MySqlConnector should report that as the "ProviderType"?

**Comment by MaceWindu** [comment]
I think I will close it.

I'm just not happy with fact that while TINYINT(1) is the same type as TINYINT it is mapped to two-value type `bool`.

**Comment by bgrainger** [comment]
Ultimately this comes from MySQL Server. https://dev.mysql.com/doc/refman/8.0/en/numeric-type-syntax.html:

> `BOOL`, `BOOLEAN`
> 
> These types are synonyms for `TINYINT(1)`. 

Since you can create a table with a `BOOL` column, it makes sense to me to automatically map that back to `System.Boolean`. If you disagree, there is a `TreatTinyAsBoolean=false` connection string option to opt out.
