### ISSUE TITLE
What are the MySqlDataReader Best Practice in order to achieve Best performance?

### ISSUE THREAD

**Issue by firephantomassasin** [mysql-net/MySqlConnector#949]
I would like to know What are the MySqlDataReader Best Practice in order to achieve Best performance?

Right now, I am doing this kind of approach to retrieve the value from `MySqlDataReader`.

```csharp
MySqlDataReader ret = await myCommand.ExecuteReaderAsync()

long result = 0;

using (ret)
                {
                    while (await ret.ReadAsync())
                    {
                        int ordinal = ret.GetOrdinal("userId");

            if (ret.IsDBNull(ordinal))
            {
                result  = 0;
            }
            else
            {
                result  = ret.GetInt64(ordinal);
            }

                    } 
                }
```

Is this okay and is this fast enough to retrieve the data? Or are there any better approach in order to achieve faster performance?

Also, I have observed that the MySqlDataReader has disposeAsync, is it recommended to use the DisposeAsync or is the Dispose the same (using (xxx))?

**Comment by bgrainger** [comment]
Firstly: https://ericlippert.com/2012/12/17/performance-rant/

To answer your questions:

`Async` methods are good for scalability, but do add a small amount of runtime overhead; using the sync methods can be faster (but will block the calling thread, which can lead to thread pool exhaustion); this decision depends a lot on your throughput.

`GetOrdinal` incurs some overhead. If you know the structure of the SQL you're existing, it would be faster to just call `IsDbNull(1)`, `GetInt64(1)`, etc.

Calling `GetInt64` is great as it avoids boxing the returned value.

If you've already read the entire result set (i.e., calling `Read(Async)` until it returns `false`), then `DisposeAsync` executes synchronously and there's not need to use it instead of `Dispose`.

These are all micro-optimisations; to evaluate performance, you should use a performance profiler. Back to Eric's post: determine if your code is fast enough, or if it needs to be improved, then evaluate where the bottlenecks are.

**Comment by firephantomassasin** [comment]
Thank you for the answer @bgrainger, one last question, is calling GetOrdinal do a network call going to the DB server? Or it just only happening on the RAM already? 


How about calling GetInt64(<column name>)? Which is more faster is the GetInt64(ordinal num) or GetInt64(column name) ?
In our case we don't really know the ordinal number, we only know which column name to retrieve.

**Comment by bgrainger** [comment]
GetOrdinal is all in-memory; just a lookup in a table of column metadata sent by the server.

`GetInt64(string)` calls `GetInt64(GetOrdinal(string))` so calling `GetInt64(int)` directly must be faster by definition, but it seems unlikely that it would make a big difference in practice. Again, a profiler is going to tell you if it makes any difference at all in your code with your environment.
