### ISSUE TITLE
MySqlInfoMessageEventArgs

### ISSUE THREAD

**Issue by cmwi2k** [mysql-net/MySqlConnector#954]
Difference between MySql.Data and MySqlConnector MySqlInfoMessageEventArgs, the official one has the property errors and MySqlConnector has Errors with a capital, stopping the drop in replacement or ability to use IDb interfaces without having to use preprocessors or change the code.

**Comment by bgrainger** [comment]
> stopping the drop in replacement

See https://github.com/mysql-net/MySqlConnector/issues/844#issuecomment-653259138: "MySqlConnector has pivoted away from its initial goal of being a binary-compatible drop-in replacement for Connector/NET, and now aims to be better."

Since one has to change the namespace to use MySqlConnector, it seems easy enough to rename the access to the property to use `Errors`, not `errors`.

> ability to use IDb interfaces without having to use preprocessors or change the code

Not sure what this means; it should be completely possible to use MySqlConnector instead of MySql.Data by using `IDbConnection` or `DbConnection`.

The namespace of the library has changed, so some code changes will, of course, be necessary.
