### ISSUE TITLE
Why does GetAwaiter().GetResult() not deadlock?

### ISSUE THREAD

**Issue by kendallb** [mysql-net/MySqlConnector#960]
We have been using MySqlConnector for some time now and it extensively uses .GetAwaiter().GetResult() to block and return the value of an async function and I have never had any deadlocks to date. However today I was working with Rebus, and decided to do the same thing and instantly hit a deadlock in a ASP.NET POST request.

Checking in Rebus itself, they have a SyncBus wrapper which uses a pretty extensive helper function to execute it's async functions synchronously which jumps through hoops to get it done, but when I use that, it works:

https://github.com/rebus-org/Rebus/blob/master/Rebus/Bus/Advanced/AsyncHelpers.cs

So my question is, why is using .GetAwaiter().GetResult() safe in the context of MySqlConnector functions, and not when using Rebus? According to Stephen Cleary, it can cause deadlocks:

https://stackoverflow.com/questions/39007006/is-getawaiter-getresult-safe-for-general-use

but perhaps it has to do with the type of async functions that are used in MySqlConnector (pretty much all socket calls), as opposed to what Rebus is using? I have seen similar AsyncHelpers in other libraries like NLog, so I am really curious why we are not seeing deadlocks with MySqlConnector, and wondering if it's just waiting for a deadlock to happen, or if it never will due to what the library is doing?

**Comment by bgrainger** [comment]
> to block and return the value of an async function

There's not a good way to do this safely AFAIK (and MySqlConnector never blocks on an async function).

More specifically, MySqlConnector only calls `GetAwaiter().GetResult()` on already-completed tasks. (Thus it never blocks and can't deadlock.)

The public sync APIs and async APIs all call into the same internal pipeline but pass `IOBehavior.Asynchronous` or `IOBehavior.Synchronous` to the internal helper methods. Those methods call helpers which call (and `await`) other helpers, which eventually end up calling an I/O method. At that point, the `IOBehavior` parameter controls whether (say) `Socket.Receive` or `Socket.ReceiveAsync`, or `Stream.Read` or `Stream.ReadAsync` is called. For example:

https://github.com/mysql-net/MySqlConnector/blob/f024997cec73ad9c533714ffd9fbe53b09fe88b5/src/MySqlConnector/Protocol/Serialization/SocketByteHandler.cs#L29-L30

(This avoids duplicating a _huge_ amount of shared code for the sync and async code paths.)

In the case of `IOBehavior.Synchronous` and `Stream.Read`, the method completes synchronously, any `await`ed `Task`s are already completed and execution proceeds synchronously all the way back to the public API. The `Task` object is already complete, so `.GetAwaiter().GetResult()` just unwraps the result (or throws the first exception on the `Task`).

This only works in MySqlConnector because the code guarantees that the `Task` has run to completion. With a non-completed `Task`, calling `.GetAwaiter().GetResult()` (or `.Wait()` or `.Result`) can easily lead to deadlock. (And for `ValueTask`, it's not even permitted at all.)

**Comment by kendallb** [comment]
Ahh that makes perfect sense now, thanks for explaining that! So the sync functions really are synchronous after all.

Time to fix a couple of potential deadlocks in our code :)

**Comment by bgrainger** [comment]
> So the sync functions really are synchronous after all.

Yes, they are, and it's necessary to write them that way to avoid deadlocks in clients using the traditional sync ADO.NET methods. (It's also a little more efficient as no compiler-generated async state machines are ever allocated on the heap; it's just "regular old" function calls all the way down.)
